import type { QuestChapterDefinition, QuestDefinitionV2 } from "../../domain";
import { coreChapter, corePresetQuest, counterGoal, inventoryGoal, milestoneGoal } from "../builders";

export const coreEndcityChapter: QuestChapterDefinition = coreChapter({
  id: "core.endcity",
  title: "龙打完了，班还没下",
  description: "外岛还有紫颂果、潜影贝、末地城和最重要的翅膀，终末远征才刚进入加时赛。",
  order: 7,
  unlockRule: { type: "quest", questId: "preset.core.end.kill_dragon", status: "completed" },
  questIds: [
    "preset.core.endcity.chorus",
    "preset.core.endcity.shulkers",
    "preset.core.endcity.shells",
    "preset.core.endcity.city",
    "preset.core.endcity.elytra",
    "preset.core.endcity.shulker_box",
    "preset.core.endcity.fly",
  ],
});

export const coreEndcityQuests: QuestDefinitionV2[] = [
  corePresetQuest({
    id: "preset.core.endcity.chorus",
    title: "这果子会替你选落点",
    description: "让背包里出现至少一个紫颂果。吃下去能瞬移，至于落在哪里，果子通常比玩家更有自己的想法。",
    completionMessage: "紫颂果已收下，随机落点服务随时待命。",
    chapterId: "core.endcity",
    order: 1,
    rarity: "common",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_chorus_fruit", "selector.item.chorus_fruit", 1, "背包中拥有一个紫颂果")],
    gold: 120,
    experience: 40,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
  }),
  corePresetQuest({
    id: "preset.core.endcity.shulkers",
    title: "盒子成精，还会让人上天",
    description: "击杀 5 只潜影贝。它们藏在方块里发射漂浮弹，打架风格主打一个拒绝脚踏实地。",
    completionMessage: "五只潜影贝下班，重力暂时重新接管现场。",
    chapterId: "core.endcity",
    order: 2,
    rarity: "rare",
    reliability: "A",
    goals: [
      counterGoal("goal.kill_shulkers", "entity.kill", 5, "击杀 5 只潜影贝", {
        filters: { entity: { op: "eq", value: "minecraft:shulker" } },
      }),
    ],
    gold: 300,
    experience: 100,
    requiredCapabilities: ["cap.event.entity.kill.v1"],
  }),
  corePresetQuest({
    id: "preset.core.endcity.shells",
    title: "随身仓库的四块拼图",
    description: "章节开放后累计获得 4 个潜影壳。它们看着像战利品，合起来却是所有囤积症玩家的福音。",
    completionMessage: "四个潜影壳到手，移动仓库开始备料。",
    chapterId: "core.endcity",
    order: 3,
    rarity: "rare",
    reliability: "A",
    goals: [
      counterGoal("goal.obtain_shulker_shells", "item.obtain", 4, "累计获得 4 个潜影壳", {
        filters: { item: { op: "eq", value: "minecraft:shulker_shell" } },
        aggregation: "sum",
        field: "amount",
      }),
    ],
    gold: 250,
    experience: 90,
    requiredCapabilities: ["cap.event.item.obtain.v1"],
  }),
  corePresetQuest({
    id: "preset.core.endcity.city",
    title: "虚空里的紫色高楼",
    description: "亲自进入一座末地城。只有经过验证的结构识别才会完成；拿到鞘翅或潜影壳不能反推你来过。",
    completionMessage: "末地城已确认，紫色高楼终于不是海市蜃楼。",
    chapterId: "core.endcity",
    order: 4,
    rarity: "epic",
    reliability: "C",
    goals: [
      milestoneGoal("goal.enter_end_city", "structure.enter", "亲自进入一座末地城", {
        filters: { structure: { op: "eq", value: "minecraft:end_city" } },
      }),
    ],
    gold: 400,
    experience: 150,
    requiredCapabilities: ["cap.event.structure.enter.v1"],
  }),
  corePresetQuest({
    id: "preset.core.endcity.elytra",
    title: "从今天起，悬崖是跑道",
    description: "让背包里出现一副鞘翅。它不会凭空保证安全，烟花、耐久和落地技术仍然需要你自己负责。",
    completionMessage: "鞘翅入手，世界地图突然变得很平。",
    chapterId: "core.endcity",
    order: 5,
    rarity: "legendary",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_elytra", "selector.item.elytra", 1, "背包中拥有一副鞘翅")],
    gold: 1200,
    experience: 600,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
  }),
  corePresetQuest({
    id: "preset.core.endcity.shulker_box",
    title: "背包不够，盒子来凑",
    description: "让背包里出现任意颜色的潜影盒。真正的后期玩家不是东西少，而是学会把杂物分进更多盒子。",
    completionMessage: "潜影盒到手，库存管理从此进入套娃时代。",
    chapterId: "core.endcity",
    order: 6,
    rarity: "epic",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_shulker_box", "selector.item.shulker_boxes", 1, "背包中拥有任意颜色的潜影盒")],
    gold: 350,
    experience: 120,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
  }),
  corePresetQuest({
    id: "preset.core.endcity.fly",
    title: "这次真的脚不沾地",
    description: "拥有鞘翅后，真正进入一次鞘翅滑翔状态。站在高处摆姿势不算，系统必须确认你已经开始滑翔。",
    completionMessage: "滑翔确认，地面交通正式降级为备选方案。",
    chapterId: "core.endcity",
    order: 7,
    rarity: "epic",
    reliability: "B",
    goals: [milestoneGoal("goal.start_elytra_glide", "player.glide", "进入一次鞘翅滑翔状态")],
    gold: 500,
    experience: 180,
    requiredCapabilities: ["cap.event.player.glide.v1"],
    unlockRule: { type: "quest", questId: "preset.core.endcity.elytra", status: "completed" },
  }),
];
