import type { QuestChapterDefinition, QuestDefinitionV2 } from "../../domain";
import { coreChapter, corePresetQuest, inventoryGoal, milestoneGoal } from "../builders";

export const coreMagicChapter: QuestChapterDefinition = coreChapter({
  id: "core.magic",
  title: "经验条也有用武之地",
  description: "把书、青金石和经验摆上桌，让普通工具学会一点不普通的本事。",
  order: 3,
  unlockRule: {
    type: "any",
    rules: [
      { type: "quest", questId: "preset.core.mining.first_diamond", status: "completed" },
      { type: "fact", factId: "fact.item.lapis_lazuli", operator: "gte", value: 1 },
    ],
  },
  questIds: [
    "preset.core.magic.enchanting_table",
    "preset.core.magic.bookshelves",
    "preset.core.magic.first_enchant",
    "preset.core.magic.anvil",
    "preset.core.magic.enchanted_book",
  ],
});

export const coreMagicQuests: QuestDefinitionV2[] = [
  corePresetQuest({
    id: "preset.core.magic.enchanting_table",
    title: "这桌子会说神秘语言",
    description: "让背包里出现一张附魔台。钻石和书没有白花，它现在负责把经验条变成真正的战斗力。",
    completionMessage: "附魔台已就位，经验终于不只负责发绿光。",
    chapterId: "core.magic",
    order: 1,
    rarity: "rare",
    reliability: "A",
    goals: [
      inventoryGoal("goal.possess_enchanting_table", "selector.item.enchanting_table", 1, "背包中拥有一张附魔台"),
    ],
    gold: 160,
    experience: 70,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
  }),
  corePresetQuest({
    id: "preset.core.magic.bookshelves",
    title: "知识摆满一整圈",
    description: "让背包里同时拥有至少 15 个书架。附魔台也讲究学习氛围，空荡荡的房间只会给你一点小惊喜。",
    completionMessage: "十五个书架到齐，附魔台开始认真上班。",
    chapterId: "core.magic",
    order: 2,
    rarity: "rare",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_bookshelves", "selector.item.bookshelves", 15, "背包中同时拥有至少 15 个书架")],
    gold: 180,
    experience: 80,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
  }),
  corePresetQuest({
    id: "preset.core.magic.first_enchant",
    title: "叮——装备学会了新招",
    description: "亲手完成一次成功附魔。拿到附魔物品才算数，光在界面里纠结词条不算魔法实践。",
    completionMessage: "第一次附魔成功，装备开始自带高光。",
    chapterId: "core.magic",
    order: 3,
    rarity: "rare",
    reliability: "B",
    goals: [milestoneGoal("goal.apply_first_enchant", "enchant.apply", "成功完成一次附魔")],
    gold: 200,
    experience: 90,
    requiredCapabilities: ["cap.event.enchant.apply.v1"],
  }),
  corePresetQuest({
    id: "preset.core.magic.anvil",
    title: "铁砧：经验粉碎机",
    description: "让背包里出现一座铁砧。它能修装备、改名字，也能用几声清脆的当当把经验条吃得干干净净。",
    completionMessage: "铁砧到位，经验和装备都准备接受重组。",
    chapterId: "core.magic",
    order: 4,
    rarity: "common",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_anvil", "selector.item.anvil", 1, "背包中拥有一座铁砧")],
    gold: 120,
    experience: 50,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
  }),
  corePresetQuest({
    id: "preset.core.magic.enchanted_book",
    title: "知识真的会发紫光",
    description: "让背包里出现一本附魔书。不管词条多离谱，先收好，没准哪天它就和某件装备看对眼了。",
    completionMessage: "附魔书已收藏，纸页里确实藏着点真本事。",
    chapterId: "core.magic",
    order: 5,
    rarity: "rare",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_enchanted_book", "selector.item.enchanted_book", 1, "背包中拥有一本附魔书")],
    gold: 150,
    experience: 60,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
  }),
];
