import type { QuestDefinitionV2 } from "../../domain";
import { corePresetQuest, counterGoal, inventoryGoal, milestoneGoal } from "../builders";

const ENTER_NETHER = { type: "quest" as const, questId: "preset.core.nether.enter", status: "completed" as const };

export const coreNetherAdditionalQuests: QuestDefinitionV2[] = [
  corePresetQuest({
    id: "preset.core.nether.quartz",
    title: "白得发亮，挖着上头",
    description: "进入下界后累计获得 16 个下界石英。它经验给得爽快，建筑也很体面，属于怎么挖都不亏。",
    completionMessage: "石英入袋，下界总算交了点像样的门票钱。",
    chapterId: "core.nether",
    order: 1.5,
    rarity: "common",
    reliability: "A",
    goals: [
      counterGoal("goal.obtain_nether_quartz", "item.obtain", 16, "累计获得 16 个下界石英", {
        filters: { item: { op: "eq", value: "minecraft:quartz" } },
        aggregation: "sum",
        field: "amount",
      }),
    ],
    gold: 100,
    experience: 35,
    requiredCapabilities: ["cap.event.item.obtain.v1"],
    unlockRule: ENTER_NETHER,
  }),
  corePresetQuest({
    id: "preset.core.nether.piglin_barter",
    title: "金锭递过去，朋友看运气",
    description: "和猪灵成功完成一次以物易物。它收金子的速度很专业，至于回礼值不值，只能尊重随机数。",
    completionMessage: "第一次猪灵交易成交，回礼至少不是空气。",
    chapterId: "core.nether",
    order: 1.75,
    rarity: "rare",
    reliability: "B",
    goals: [milestoneGoal("goal.complete_piglin_barter", "piglin.barter", "成功完成一次猪灵以物易物")],
    gold: 180,
    experience: 70,
    requiredCapabilities: ["cap.event.piglin.barter.v1"],
    unlockRule: ENTER_NETHER,
  }),
  corePresetQuest({
    id: "preset.core.nether.blaze_rods",
    title: "火柴棍，但脾气更大",
    description: "进入下界后累计获得 8 根烈焰棒。它们是酿造和末影之眼的硬通货，别顺手全磨成粉。",
    completionMessage: "烈焰棒攒够，炼药与寻龙两条路都通了。",
    chapterId: "core.nether",
    order: 2.5,
    rarity: "rare",
    reliability: "A",
    goals: [
      counterGoal("goal.obtain_blaze_rods", "item.obtain", 8, "累计获得 8 根烈焰棒", {
        filters: { item: { op: "eq", value: "minecraft:blaze_rod" } },
        aggregation: "sum",
        field: "amount",
      }),
    ],
    gold: 220,
    experience: 90,
    requiredCapabilities: ["cap.event.item.obtain.v1"],
    unlockRule: ENTER_NETHER,
  }),
  corePresetQuest({
    id: "preset.core.nether.nether_wart",
    title: "长得诡异，药效正规",
    description: "让背包里出现至少一个下界疣。别被它皱巴巴的外表劝退，大多数正经药水都得先从它开始。",
    completionMessage: "下界疣到手，酿造锅里终于有了第一味。",
    chapterId: "core.nether",
    order: 6,
    rarity: "common",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_nether_wart", "selector.item.nether_wart", 1, "背包中拥有至少一个下界疣")],
    gold: 120,
    experience: 40,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
    unlockRule: ENTER_NETHER,
  }),
  corePresetQuest({
    id: "preset.core.nether.brewing_stand",
    title: "炼药台开张，概不赊账",
    description: "在获得烈焰棒后，让背包里出现一座酿造台。水瓶、材料和燃料各就各位，魔药生意可以开张了。",
    completionMessage: "酿造台已开工，瓶瓶罐罐开始讲科学。",
    chapterId: "core.nether",
    order: 7,
    rarity: "common",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_brewing_stand", "selector.item.brewing_stand", 1, "背包中拥有一座酿造台")],
    gold: 150,
    experience: 60,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
    unlockRule: { type: "quest", questId: "preset.core.nether.blaze_rods", status: "completed" },
  }),
  corePresetQuest({
    id: "preset.core.nether.ancient_debris",
    title: "挖到这块，今天值了",
    description: "进入下界后累计获得第一块远古残骸。它低调得像普通石头，身价却足够让整趟爆破都变得合理。",
    completionMessage: "远古残骸出土，合金升级终于不再是传说。",
    chapterId: "core.nether",
    order: 8,
    rarity: "epic",
    reliability: "A",
    goals: [
      counterGoal("goal.obtain_ancient_debris", "item.obtain", 1, "获得第一块远古残骸", {
        filters: { item: { op: "eq", value: "minecraft:ancient_debris" } },
        aggregation: "sum",
        field: "amount",
      }),
    ],
    gold: 300,
    experience: 120,
    requiredCapabilities: ["cap.event.item.obtain.v1"],
    unlockRule: ENTER_NETHER,
  }),
  corePresetQuest({
    id: "preset.core.nether.netherite_ingot",
    title: "紫黑小锭，身价离谱",
    description: "在发现远古残骸后，让背包里同时拥有至少一个下界合金锭。四份碎片加四块金，贵得很有道理。",
    completionMessage: "下界合金锭到手，装备升级排上日程。",
    chapterId: "core.nether",
    order: 9,
    rarity: "epic",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_netherite_ingot", "selector.item.netherite_ingot", 1, "背包中拥有下界合金锭")],
    gold: 500,
    experience: 180,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
    unlockRule: { type: "quest", questId: "preset.core.nether.ancient_debris", status: "completed" },
  }),
];
