/* This file is generated by design/menu-ui/build.py --quest-icons. */

export interface GeneratedQuestIconTheme {
  marker: string;
  texture: string;
}

export const GENERATED_PRESET_QUEST_ICONS: Readonly<Record<string, GeneratedQuestIconTheme>> = {
  "preset.core.survival.first_log": {
    marker: "§r§0§0§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_survival_first_log",
  },
  "preset.core.survival.crafting_table": {
    marker: "§r§0§1§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_survival_crafting_table",
  },
  "preset.core.survival.stone_pickaxe": {
    marker: "§r§0§2§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_survival_stone_pickaxe",
  },
  "preset.core.survival.torches": {
    marker: "§r§0§3§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_survival_torches",
  },
  "preset.core.survival.furnace": {
    marker: "§r§0§4§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_survival_furnace",
  },
  "preset.core.survival.bed": {
    marker: "§r§0§5§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_survival_bed",
  },
  "preset.core.survival.shield": {
    marker: "§r§0§6§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_survival_shield",
  },
  "preset.core.mining.iron_ingots": {
    marker: "§r§0§7§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_mining_iron_ingots",
  },
  "preset.core.mining.iron_pickaxe": {
    marker: "§r§0§8§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_mining_iron_pickaxe",
  },
  "preset.core.mining.bucket": {
    marker: "§r§0§9§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_mining_bucket",
  },
  "preset.core.mining.full_iron_armor": {
    marker: "§r§0§a§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_mining_full_iron_armor",
  },
  "preset.core.mining.redstone": {
    marker: "§r§0§b§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_mining_redstone",
  },
  "preset.core.mining.lapis": {
    marker: "§r§0§c§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_mining_lapis",
  },
  "preset.core.mining.first_diamond": {
    marker: "§r§0§d§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_mining_first_diamond",
  },
  "preset.core.mining.diamond_miner": {
    marker: "§r§0§e§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_mining_diamond_miner",
  },
  "preset.core.mining.diamond_pickaxe": {
    marker: "§r§0§f§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_mining_diamond_pickaxe",
  },
  "preset.core.mining.obsidian": {
    marker: "§r§1§0§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_mining_obsidian",
  },
  "preset.core.magic.enchanting_table": {
    marker: "§r§1§1§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_magic_enchanting_table",
  },
  "preset.core.magic.bookshelves": {
    marker: "§r§1§2§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_magic_bookshelves",
  },
  "preset.core.magic.first_enchant": {
    marker: "§r§1§3§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_magic_first_enchant",
  },
  "preset.core.magic.anvil": {
    marker: "§r§1§4§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_magic_anvil",
  },
  "preset.core.magic.enchanted_book": {
    marker: "§r§1§5§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_magic_enchanted_book",
  },
  "preset.core.nether.enter": {
    marker: "§r§1§6§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_nether_enter",
  },
  "preset.core.nether.quartz": {
    marker: "§r§1§7§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_nether_quartz",
  },
  "preset.core.nether.piglin_barter": {
    marker: "§r§1§8§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_nether_piglin_barter",
  },
  "preset.core.nether.blaze_hunter": {
    marker: "§r§1§9§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_nether_blaze_hunter",
  },
  "preset.core.nether.blaze_rods": {
    marker: "§r§1§a§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_nether_blaze_rods",
  },
  "preset.core.nether.nether_wart": {
    marker: "§r§1§b§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_nether_nether_wart",
  },
  "preset.core.nether.brewing_stand": {
    marker: "§r§1§c§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_nether_brewing_stand",
  },
  "preset.core.nether.ancient_debris": {
    marker: "§r§1§d§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_nether_ancient_debris",
  },
  "preset.core.nether.netherite_ingot": {
    marker: "§r§1§e§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_nether_netherite_ingot",
  },
  "preset.core.eye.ender_pearls": {
    marker: "§r§1§f§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_eye_ender_pearls",
  },
  "preset.core.eye.blaze_powder": {
    marker: "§r§2§0§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_eye_blaze_powder",
  },
  "preset.core.eye.eyes": {
    marker: "§r§2§1§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_eye_eyes",
  },
  "preset.core.eye.stronghold": {
    marker: "§r§2§2§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_eye_stronghold",
  },
  "preset.core.eye.enter_end": {
    marker: "§r§2§3§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_eye_enter_end",
  },
  "preset.core.end.kill_dragon": {
    marker: "§r§2§4§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_end_kill_dragon",
  },
  "preset.core.end.dragon_breath": {
    marker: "§r§2§5§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_end_dragon_breath",
  },
  "preset.core.end.gateway": {
    marker: "§r§2§6§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_end_gateway",
  },
  "preset.core.endcity.chorus": {
    marker: "§r§2§7§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_endcity_chorus",
  },
  "preset.core.endcity.shulkers": {
    marker: "§r§2§8§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_endcity_shulkers",
  },
  "preset.core.endcity.shells": {
    marker: "§r§2§9§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_endcity_shells",
  },
  "preset.core.endcity.city": {
    marker: "§r§2§a§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_endcity_city",
  },
  "preset.core.endcity.elytra": {
    marker: "§r§2§b§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_endcity_elytra",
  },
  "preset.core.endcity.shulker_box": {
    marker: "§r§2§c§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_endcity_shulker_box",
  },
  "preset.core.endcity.fly": {
    marker: "§r§2§d§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_endcity_fly",
  },
  "preset.core.apex.wither_skulls": {
    marker: "§r§2§e§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_apex_wither_skulls",
  },
  "preset.core.apex.kill_wither": {
    marker: "§r§2§f§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_apex_kill_wither",
  },
  "preset.core.apex.nether_star": {
    marker: "§r§3§0§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_apex_nether_star",
  },
  "preset.core.apex.beacon": {
    marker: "§r§3§1§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_apex_beacon",
  },
  "preset.core.apex.full_beacon": {
    marker: "§r§3§2§r",
    texture: "textures/ui/creeper_menu/quest_icons/core_apex_full_beacon",
  },
  "preset.world.village.first_trade": {
    marker: "§r§3§3§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_village_first_trade",
  },
  "preset.world.village.trader": {
    marker: "§r§3§4§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_village_trader",
  },
  "preset.world.village.cure": {
    marker: "§r§3§5§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_village_cure",
  },
  "preset.world.village.ominous_bottle": {
    marker: "§r§3§6§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_village_ominous_bottle",
  },
  "preset.world.village.raid": {
    marker: "§r§3§7§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_village_raid",
  },
  "preset.world.village.totem": {
    marker: "§r§3§8§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_village_totem",
  },
  "preset.world.ocean.enter": {
    marker: "§r§3§9§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_ocean_enter",
  },
  "preset.world.ocean.treasure_map": {
    marker: "§r§3§a§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_ocean_treasure_map",
  },
  "preset.world.ocean.heart": {
    marker: "§r§3§b§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_ocean_heart",
  },
  "preset.world.ocean.guardians": {
    marker: "§r§3§c§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_ocean_guardians",
  },
  "preset.world.ocean.elder_guardian": {
    marker: "§r§3§d§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_ocean_elder_guardian",
  },
  "preset.world.ocean.sponge": {
    marker: "§r§3§e§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_ocean_sponge",
  },
  "preset.world.ocean.conduit": {
    marker: "§r§3§f§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_ocean_conduit",
  },
  "preset.world.archaeology.brush": {
    marker: "§r§4§0§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_archaeology_brush",
  },
  "preset.world.archaeology.brush_suspicious": {
    marker: "§r§4§1§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_archaeology_brush_suspicious",
  },
  "preset.world.archaeology.sherd": {
    marker: "§r§4§2§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_archaeology_sherd",
  },
  "preset.world.archaeology.pot": {
    marker: "§r§4§3§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_archaeology_pot",
  },
  "preset.world.archaeology.sniffer_egg": {
    marker: "§r§4§4§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_archaeology_sniffer_egg",
  },
  "preset.world.archaeology.ancient_plants": {
    marker: "§r§4§5§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_archaeology_ancient_plants",
  },
  "preset.world.deepdark.sculk": {
    marker: "§r§4§6§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_deepdark_sculk",
  },
  "preset.world.deepdark.enter": {
    marker: "§r§4§7§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_deepdark_enter",
  },
  "preset.world.deepdark.ancient_city": {
    marker: "§r§4§8§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_deepdark_ancient_city",
  },
  "preset.world.deepdark.echo_shard": {
    marker: "§r§4§9§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_deepdark_echo_shard",
  },
  "preset.world.deepdark.recovery_compass": {
    marker: "§r§4§a§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_deepdark_recovery_compass",
  },
  "preset.world.deepdark.swift_sneak": {
    marker: "§r§4§b§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_deepdark_swift_sneak",
  },
  "preset.world.trials.enter": {
    marker: "§r§4§c§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_trials_enter",
  },
  "preset.world.trials.breeze": {
    marker: "§r§4§d§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_trials_breeze",
  },
  "preset.world.trials.breeze_rod": {
    marker: "§r§4§e§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_trials_breeze_rod",
  },
  "preset.world.trials.trial_key": {
    marker: "§r§4§f§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_trials_trial_key",
  },
  "preset.world.trials.vault": {
    marker: "§r§5§0§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_trials_vault",
  },
  "preset.world.trials.ominous": {
    marker: "§r§5§1§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_trials_ominous",
  },
  "preset.world.trials.ominous_key": {
    marker: "§r§5§2§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_trials_ominous_key",
  },
  "preset.world.trials.heavy_core": {
    marker: "§r§5§3§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_trials_heavy_core",
  },
  "preset.world.trials.mace": {
    marker: "§r§5§4§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_trials_mace",
  },
  "preset.world.farm.plant": {
    marker: "§r§5§5§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_farm_plant",
  },
  "preset.world.farm.harvest": {
    marker: "§r§5§6§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_farm_harvest",
  },
  "preset.world.farm.breed": {
    marker: "§r§5§7§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_farm_breed",
  },
  "preset.world.farm.rancher": {
    marker: "§r§5§8§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_farm_rancher",
  },
  "preset.world.farm.tame": {
    marker: "§r§5§9§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_farm_tame",
  },
  "preset.world.farm.honey": {
    marker: "§r§5§a§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_farm_honey",
  },
  "preset.world.redstone.redstone": {
    marker: "§r§5§b§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_redstone_redstone",
  },
  "preset.world.redstone.piston": {
    marker: "§r§5§c§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_redstone_piston",
  },
  "preset.world.redstone.observer": {
    marker: "§r§5§d§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_redstone_observer",
  },
  "preset.world.redstone.comparator": {
    marker: "§r§5§e§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_redstone_comparator",
  },
  "preset.world.redstone.hopper": {
    marker: "§r§5§f§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_redstone_hopper",
  },
  "preset.world.redstone.crafter": {
    marker: "§r§6§0§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_redstone_crafter",
  },
  "preset.world.redstone.crafter_use": {
    marker: "§r§6§1§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_redstone_crafter_use",
  },
  "preset.world.pale_garden.enter": {
    marker: "§r§6§2§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_pale_garden_enter",
  },
  "preset.world.pale_garden.pale_oak": {
    marker: "§r§6§3§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_pale_garden_pale_oak",
  },
  "preset.world.pale_garden.creaking": {
    marker: "§r§6§4§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_pale_garden_creaking",
  },
  "preset.world.pale_garden.heart": {
    marker: "§r§6§5§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_pale_garden_heart",
  },
  "preset.world.pale_garden.resin": {
    marker: "§r§6§6§r",
    texture: "textures/ui/creeper_menu/quest_icons/world_pale_garden_resin",
  },
  "preset.creeper.guide.open_menu": {
    marker: "§r§6§7§r",
    texture: "textures/ui/creeper_menu/quest_icons/creeper_guide_open_menu",
  },
  "preset.creeper.guide.waypoint": {
    marker: "§r§6§8§r",
    texture: "textures/ui/creeper_menu/quest_icons/creeper_guide_waypoint",
  },
  "preset.creeper.guide.tpa": {
    marker: "§r§6§9§r",
    texture: "textures/ui/creeper_menu/quest_icons/creeper_guide_tpa",
  },
  "preset.creeper.guide.random_tp": {
    marker: "§r§6§a§r",
    texture: "textures/ui/creeper_menu/quest_icons/creeper_guide_random_tp",
  },
  "preset.creeper.guide.land": {
    marker: "§r§6§b§r",
    texture: "textures/ui/creeper_menu/quest_icons/creeper_guide_land",
  },
  "preset.creeper.guide.public_waypoint": {
    marker: "§r§6§c§r",
    texture: "textures/ui/creeper_menu/quest_icons/creeper_guide_public_waypoint",
  },
  "preset.creeper.guide.market": {
    marker: "§r§6§d§r",
    texture: "textures/ui/creeper_menu/quest_icons/creeper_guide_market",
  },
  "preset.creeper.guide.red_packet": {
    marker: "§r§6§e§r",
    texture: "textures/ui/creeper_menu/quest_icons/creeper_guide_red_packet",
  },
  "preset.creeper.guide.guild": {
    marker: "§r§6§f§r",
    texture: "textures/ui/creeper_menu/quest_icons/creeper_guide_guild",
  },
  "preset.update.copper.ingots": {
    marker: "§r§7§0§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_copper_ingots",
  },
  "preset.update.copper.pickaxe": {
    marker: "§r§7§1§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_copper_pickaxe",
  },
  "preset.update.copper.full_armor": {
    marker: "§r§7§2§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_copper_full_armor",
  },
  "preset.update.copper.golem": {
    marker: "§r§7§3§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_copper_golem",
  },
  "preset.update.copper.chest": {
    marker: "§r§7§4§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_copper_chest",
  },
  "preset.update.copper.sorting": {
    marker: "§r§7§5§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_copper_sorting",
  },
  "preset.update.copper.shelf": {
    marker: "§r§7§6§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_copper_shelf",
  },
  "preset.update.skies.dried_ghast": {
    marker: "§r§7§7§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_skies_dried_ghast",
  },
  "preset.update.skies.revive": {
    marker: "§r§7§8§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_skies_revive",
  },
  "preset.update.skies.ghastling": {
    marker: "§r§7§9§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_skies_ghastling",
  },
  "preset.update.skies.happy_ghast": {
    marker: "§r§7§a§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_skies_happy_ghast",
  },
  "preset.update.skies.harness": {
    marker: "§r§7§b§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_skies_harness",
  },
  "preset.update.skies.ride": {
    marker: "§r§7§c§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_skies_ride",
  },
  "preset.update.mounts.spear": {
    marker: "§r§7§d§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_mounts_spear",
  },
  "preset.update.mounts.spear_charge": {
    marker: "§r§7§e§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_mounts_spear_charge",
  },
  "preset.update.mounts.zombie_horse": {
    marker: "§r§7§f§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_mounts_zombie_horse",
  },
  "preset.update.mounts.camel_husk": {
    marker: "§r§8§0§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_mounts_camel_husk",
  },
  "preset.update.mounts.parched": {
    marker: "§r§8§1§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_mounts_parched",
  },
  "preset.update.mounts.nautilus": {
    marker: "§r§8§2§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_mounts_nautilus",
  },
  "preset.update.mounts.ride_nautilus": {
    marker: "§r§8§3§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_mounts_ride_nautilus",
  },
  "preset.update.tiny.name_tag": {
    marker: "§r§8§4§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_tiny_name_tag",
  },
  "preset.update.tiny.name_baby": {
    marker: "§r§8§5§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_tiny_name_baby",
  },
  "preset.update.tiny.golden_dandelion": {
    marker: "§r§8§6§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_tiny_golden_dandelion",
  },
  "preset.update.tiny.baby_collection": {
    marker: "§r§8§7§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_tiny_baby_collection",
  },
  "preset.update.tiny.trumpet": {
    marker: "§r§8§8§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_tiny_trumpet",
  },
  "preset.update.chaos.sulfur": {
    marker: "§r§8§9§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_chaos_sulfur",
  },
  "preset.update.chaos.cinnabar": {
    marker: "§r§8§a§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_chaos_cinnabar",
  },
  "preset.update.chaos.cave": {
    marker: "§r§8§b§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_chaos_cave",
  },
  "preset.update.chaos.meet_cube": {
    marker: "§r§8§c§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_chaos_meet_cube",
  },
  "preset.update.chaos.bucket_cube": {
    marker: "§r§8§d§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_chaos_bucket_cube",
  },
  "preset.update.chaos.feed_cube": {
    marker: "§r§8§e§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_chaos_feed_cube",
  },
  "preset.update.chaos.tnt": {
    marker: "§r§8§f§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_chaos_tnt",
  },
  "preset.update.chaos.geyser": {
    marker: "§r§9§0§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_chaos_geyser",
  },
  "preset.update.chaos.bounce_disc": {
    marker: "§r§9§1§r",
    texture: "textures/ui/creeper_menu/quest_icons/update_chaos_bounce_disc",
  },
  "preset.experiment.drop3.dappled_forest": {
    marker: "§r§9§2§r",
    texture: "textures/ui/creeper_menu/quest_icons/experiment_drop3_dappled_forest",
  },
  "preset.experiment.drop3.poplar": {
    marker: "§r§9§3§r",
    texture: "textures/ui/creeper_menu/quest_icons/experiment_drop3_poplar",
  },
  "preset.experiment.drop3.shelf_mushroom": {
    marker: "§r§9§4§r",
    texture: "textures/ui/creeper_menu/quest_icons/experiment_drop3_shelf_mushroom",
  },
  "preset.experiment.drop3.red_shrub": {
    marker: "§r§9§5§r",
    texture: "textures/ui/creeper_menu/quest_icons/experiment_drop3_red_shrub",
  },
  "preset.experiment.drop3.camp": {
    marker: "§r§9§6§r",
    texture: "textures/ui/creeper_menu/quest_icons/experiment_drop3_camp",
  },
  "preset.experiment.drop3.straw_bed": {
    marker: "§r§9§7§r",
    texture: "textures/ui/creeper_menu/quest_icons/experiment_drop3_straw_bed",
  },
  "preset.experiment.drop3.cushion": {
    marker: "§r§9§8§r",
    texture: "textures/ui/creeper_menu/quest_icons/experiment_drop3_cushion",
  },
  "preset.hidden.warden": {
    marker: "§r§9§9§r",
    texture: "textures/ui/creeper_menu/quest_icons/hidden_warden",
  },
  "preset.hidden.dragon_again": {
    marker: "§r§9§a§r",
    texture: "textures/ui/creeper_menu/quest_icons/hidden_dragon_again",
  },
  "preset.hidden.mace_smash": {
    marker: "§r§9§b§r",
    texture: "textures/ui/creeper_menu/quest_icons/hidden_mace_smash",
  },
  "preset.hidden.happy_ghast_party": {
    marker: "§r§9§c§r",
    texture: "textures/ui/creeper_menu/quest_icons/hidden_happy_ghast_party",
  },
  "preset.hidden.elytra_distance": {
    marker: "§r§9§d§r",
    texture: "textures/ui/creeper_menu/quest_icons/hidden_elytra_distance",
  },
};
