import type { QuestChapterDefinition, QuestDefinitionV2, QuestPackDefinition } from "../../domain";
import { counterGoal, inventoryGoal, milestoneGoal, updateChapter, updatePresetQuest } from "../builders";

const PACK_ID = "preset.update.chaos" as const;
const CONTENT_CAP = "cap.content.minecraft.chaos_cubed.v1";

export const updateChaosChapter: QuestChapterDefinition = updateChapter(PACK_ID, {
  id: "update.chaos",
  title: "方块开始乱来，物理负责请假",
  description: "硫磺、朱砂、会吃方块的怪物和把人弹上天的喷泉，共同组成一场地底危险实验。",
  order: 1,
  unlockRule: { type: "always" },
  questIds: [
    "preset.update.chaos.sulfur",
    "preset.update.chaos.cinnabar",
    "preset.update.chaos.cave",
    "preset.update.chaos.meet_cube",
    "preset.update.chaos.bucket_cube",
    "preset.update.chaos.feed_cube",
    "preset.update.chaos.tnt",
    "preset.update.chaos.geyser",
    "preset.update.chaos.bounce_disc",
  ],
});

export const updateChaosQuests: QuestDefinitionV2[] = [
  updatePresetQuest(PACK_ID, {
    id: "preset.update.chaos.sulfur",
    title: "黄色矿物，先挖十六份",
    description: "任务包开启后累计获得 16 份硫磺相关基础材料。只统计稳定集合成员，其他黄色方块不能混进来凑数。",
    completionMessage: "硫磺材料达到十六份，危险实验有了基础库存。",
    chapterId: "update.chaos",
    order: 1,
    rarity: "common",
    reliability: "A",
    goals: [
      counterGoal("goal.obtain_sulfur_materials", "item.obtain", 16, "累计获得 16 份硫磺基础材料", {
        selectorId: "selector.item.sulfur_materials",
        aggregation: "sum",
        field: "amount",
      }),
    ],
    gold: 120,
    experience: 40,
    requiredCapabilities: [CONTENT_CAP, "cap.event.item.obtain.v1"],
  }),
  updatePresetQuest(PACK_ID, {
    id: "preset.update.chaos.cinnabar",
    title: "鲜红矿石，库存也要十六",
    description: "任务包开启后累计获得 16 份朱砂相关基础材料。系统按稳定 selector 统计，不看显示名称猜矿物。",
    completionMessage: "朱砂材料达到十六份，红色库存正式成堆。",
    chapterId: "update.chaos",
    order: 2,
    rarity: "common",
    reliability: "A",
    goals: [
      counterGoal("goal.obtain_cinnabar_materials", "item.obtain", 16, "累计获得 16 份朱砂基础材料", {
        selectorId: "selector.item.cinnabar_materials",
        aggregation: "sum",
        field: "amount",
      }),
    ],
    gold: 120,
    experience: 40,
    requiredCapabilities: [CONTENT_CAP, "cap.event.item.obtain.v1"],
  }),
  updatePresetQuest(PACK_ID, {
    id: "preset.update.chaos.cave",
    title: "洞穴发黄，空气可疑",
    description: "亲自进入硫磺洞穴生物群系。系统必须确认当前区域，背包里带着硫磺不能冒充地底异境到访记录。",
    completionMessage: "硫磺洞穴已抵达，地底气氛开始不讲常理。",
    chapterId: "update.chaos",
    order: 3,
    rarity: "rare",
    reliability: "B",
    goals: [
      milestoneGoal("goal.enter_sulfur_caves", "player.biome_enter", "进入硫磺洞穴生物群系", {
        filters: { biome: { op: "eq", value: "minecraft:sulfur_caves" } },
        backfillPolicy: "current_state",
        evidenceProviderId: "evidence.biome.current",
      }),
    ],
    gold: 250,
    experience: 90,
    requiredCapabilities: [CONTENT_CAP, "cap.event.player.biome_enter.v1"],
  }),
  updatePresetQuest(PACK_ID, {
    id: "preset.update.chaos.meet_cube",
    title: "方块长腿，还会盯人",
    description: "与硫磺方块怪产生一次有效接触或交互。必须由专用遭遇 Adapter 确认，远处看到它弹一下不算正式认识。",
    completionMessage: "硫磺方块怪遭遇已记录，奇怪生物又多一种。",
    chapterId: "update.chaos",
    order: 4,
    rarity: "rare",
    reliability: "B",
    goals: [milestoneGoal("goal.encounter_sulfur_cube", "sulfur_cube.encounter", "与硫磺方块怪产生一次有效遭遇")],
    gold: 180,
    experience: 60,
    requiredCapabilities: [CONTENT_CAP, "cap.event.sulfur_cube.encounter.v1"],
  }),
  updatePresetQuest(PACK_ID, {
    id: "preset.update.chaos.bucket_cube",
    title: "会动的方块，打桶带走",
    description: "让背包里出现一桶硫磺方块怪。必须匹配正式桶装物品 identifier，普通水桶里写个名字不能算。",
    completionMessage: "硫磺方块怪成功装桶，奇怪宠物可以随身携带。",
    chapterId: "update.chaos",
    order: 5,
    rarity: "epic",
    reliability: "A",
    goals: [
      inventoryGoal(
        "goal.possess_bucketed_sulfur_cube",
        "selector.item.bucket_of_sulfur_cube",
        1,
        "背包中拥有一桶硫磺方块怪"
      ),
    ],
    gold: 300,
    experience: 100,
    requiredCapabilities: [CONTENT_CAP, "cap.snapshot.inventory.v1"],
  }),
  updatePresetQuest(PACK_ID, {
    id: "preset.update.chaos.feed_cube",
    title: "它真不挑食，方块也吃",
    description: "成功让硫磺方块怪吸收一种受支持的方块。递出方块不算，必须确认吸收完成并产生对应玩法结果。",
    completionMessage: "第一次方块投喂成功，它的菜单果然很宽。",
    chapterId: "update.chaos",
    order: 6,
    rarity: "epic",
    reliability: "B",
    goals: [milestoneGoal("goal.feed_sulfur_cube", "sulfur_cube.feed_success", "让硫磺方块怪成功吸收一种方块")],
    gold: 300,
    experience: 100,
    requiredCapabilities: [CONTENT_CAP, "cap.event.sulfur_cube.feed_success.v1"],
    unlockRule: { type: "quest", questId: "preset.update.chaos.meet_cube", status: "completed" },
  }),
  updatePresetQuest(PACK_ID, {
    id: "preset.update.chaos.tnt",
    title: "喂它 TNT，科研精神拉满",
    description: "让硫磺方块怪吸收 TNT 并完成对应特殊玩法。必须由专用挑战 Adapter 验证完整结果，普通爆炸不能代打。",
    completionMessage: "TNT 特殊投喂完成，危险实验成功且暂时完整。",
    chapterId: "update.chaos",
    order: 7,
    rarity: "epic",
    reliability: "C",
    goals: [milestoneGoal("goal.feed_sulfur_cube_tnt", "sulfur_cube.feed_tnt", "让硫磺方块怪完成 TNT 特殊玩法")],
    gold: 500,
    experience: 180,
    requiredCapabilities: [CONTENT_CAP, "cap.challenge.sulfur_cube.feed_tnt.v1"],
    unlockRule: { type: "quest", questId: "preset.update.chaos.feed_cube", status: "completed" },
  }),
  updatePresetQuest(PACK_ID, {
    id: "preset.update.chaos.geyser",
    title: "地底喷泉，单程上天",
    description: "被硫磺喷泉有效弹射一次。必须确认玩家由喷泉产生位移和弹射状态，自己跳起来不能假装地质活动。",
    completionMessage: "硫磺喷泉弹射成功，重力短暂失去发言权。",
    chapterId: "update.chaos",
    order: 8,
    rarity: "epic",
    reliability: "B",
    goals: [milestoneGoal("goal.launch_from_geyser", "geyser.launch_player", "被硫磺喷泉有效弹射一次")],
    gold: 350,
    experience: 120,
    requiredCapabilities: [CONTENT_CAP, "cap.challenge.geyser.launch_player.v1"],
    unlockRule: { type: "quest", questId: "preset.update.chaos.cave", status: "completed" },
  }),
  updatePresetQuest(PACK_ID, {
    id: "preset.update.chaos.bounce_disc",
    title: "Bounce！唱片拒绝安静",
    description: "让背包里出现一张 Bounce 音乐唱片。必须匹配正式唱片 identifier，改名后的普通唱片不会骗过 selector。",
    completionMessage: "Bounce 唱片入手，混沌冒险有了专属背景音乐。",
    chapterId: "update.chaos",
    order: 9,
    rarity: "legendary",
    reliability: "A",
    goals: [
      inventoryGoal("goal.possess_bounce_disc", "selector.item.bounce_music_disc", 1, "背包中拥有 Bounce 音乐唱片"),
    ],
    gold: 700,
    experience: 260,
    requiredCapabilities: [CONTENT_CAP, "cap.snapshot.inventory.v1"],
    unlockRule: { type: "quest", questId: "preset.update.chaos.cave", status: "completed" },
  }),
];

export const updateChaosPack: QuestPackDefinition = {
  id: PACK_ID,
  version: 1,
  title: "混沌方块，地底开席",
  description: "硫磺方块怪与喷泉挑战组成独立更新包；默认关闭，26.30 内容存在性和专用 Adapter 通过后启用。",
  category: "update",
  defaultEnabled: false,
  releaseState: "active",
  requiredCapabilities: [CONTENT_CAP],
  requiredGameplayExperiments: [],
  chapterIds: [updateChaosChapter.id],
};
