import type { QuestChapterDefinition, QuestDefinitionV2, QuestPackDefinition } from "../../domain";
import { counterGoal, inventoryGoal, milestoneGoal, snapshotGoal, updateChapter, updatePresetQuest } from "../builders";

const PACK_ID = "preset.update.copper" as const;
const CONTENT_CAP = "cap.content.minecraft.copper_age.v1";

export const updateCopperChapter: QuestChapterDefinition = updateChapter(PACK_ID, {
  id: "update.copper",
  title: "铜器时代，终于不只避雷",
  description: "从铜镐和铜甲一路做到铜傀儡自动整理，让仓库和装备都染上一层会氧化的工业色。",
  order: 1,
  unlockRule: { type: "always" },
  questIds: [
    "preset.update.copper.ingots",
    "preset.update.copper.pickaxe",
    "preset.update.copper.full_armor",
    "preset.update.copper.golem",
    "preset.update.copper.chest",
    "preset.update.copper.sorting",
    "preset.update.copper.shelf",
  ],
});

export const updateCopperQuests: QuestDefinitionV2[] = [
  updatePresetQuest(PACK_ID, {
    id: "preset.update.copper.ingots",
    title: "三十二块铜，工业起步",
    description: "任务包开启后累计获得 32 个铜锭。别急着全做避雷针，新一代工具、装备和机器都在排队要材料。",
    completionMessage: "铜锭库存达标，铜器时代正式开工。",
    chapterId: "update.copper",
    order: 1,
    rarity: "common",
    reliability: "A",
    goals: [
      counterGoal("goal.obtain_copper_ingots", "item.obtain", 32, "累计获得 32 个铜锭", {
        filters: { item: { op: "eq", value: "minecraft:copper_ingot" } },
        aggregation: "sum",
        field: "amount",
      }),
    ],
    gold: 120,
    experience: 40,
    requiredCapabilities: [CONTENT_CAP, "cap.event.item.obtain.v1"],
  }),
  updatePresetQuest(PACK_ID, {
    id: "preset.update.copper.pickaxe",
    title: "石镐和铁镐之间，有铜镐",
    description: "让背包里出现一把铜镐。它填上了工具进阶的一段空档，也让铜锭终于能堂堂正正地下矿。",
    completionMessage: "铜镐到手，矿工工具箱增加了新档位。",
    chapterId: "update.copper",
    order: 2,
    rarity: "common",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_copper_pickaxe", "selector.item.copper_pickaxe", 1, "背包中拥有一把铜镐")],
    gold: 120,
    experience: 40,
    requiredCapabilities: [CONTENT_CAP, "cap.snapshot.inventory.v1"],
  }),
  updatePresetQuest(PACK_ID, {
    id: "preset.update.copper.full_armor",
    title: "全套铜装，氧化前合影",
    description: "把铜头盔、胸甲、护腿和靴子全部穿好。四个装备槽必须同时匹配，背包里放一套备用不算全副武装。",
    completionMessage: "四件铜甲穿戴齐全，铜色防线正式成型。",
    chapterId: "update.copper",
    order: 3,
    rarity: "rare",
    reliability: "A",
    goals: [
      snapshotGoal("goal.equip_copper_helmet", "equipment", "selector.equipment.copper_helmet", 1, "穿上铜头盔"),
      snapshotGoal(
        "goal.equip_copper_chestplate",
        "equipment",
        "selector.equipment.copper_chestplate",
        1,
        "穿上铜胸甲"
      ),
      snapshotGoal("goal.equip_copper_leggings", "equipment", "selector.equipment.copper_leggings", 1, "穿上铜护腿"),
      snapshotGoal("goal.equip_copper_boots", "equipment", "selector.equipment.copper_boots", 1, "穿上铜靴子"),
    ],
    gold: 260,
    experience: 90,
    requiredCapabilities: [CONTENT_CAP, "cap.snapshot.equipment.v1"],
  }),
  updatePresetQuest(PACK_ID, {
    id: "preset.update.copper.golem",
    title: "铜块一动，机械伙伴报到",
    description: "由你成功生成一只铜傀儡。摆好材料只是准备，必须通过专用归属证据确认这个机械伙伴确实因你诞生。",
    completionMessage: "铜傀儡成功启动，仓库迎来新员工。",
    chapterId: "update.copper",
    order: 4,
    rarity: "epic",
    reliability: "B",
    goals: [
      milestoneGoal("goal.create_copper_golem", "copper_golem.create", "成功生成一只铜傀儡", {
        backfillPolicy: "historical",
        evidenceProviderId: "evidence.copper_golem.owner",
      }),
    ],
    gold: 350,
    experience: 120,
    requiredCapabilities: [CONTENT_CAP, "cap.event.copper_golem.create.v1"],
  }),
  updatePresetQuest(PACK_ID, {
    id: "preset.update.copper.chest",
    title: "仓库也开始穿铜皮",
    description: "让背包里出现一个铜箱子。它不仅换了材质，还准备和铜傀儡一起把杂乱库存变成自动化流水线。",
    completionMessage: "铜箱子到手，智能仓库有了第一只容器。",
    chapterId: "update.copper",
    order: 5,
    rarity: "rare",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_copper_chest", "selector.item.copper_chest", 1, "背包中拥有一个铜箱子")],
    gold: 220,
    experience: 80,
    requiredCapabilities: [CONTENT_CAP, "cap.snapshot.inventory.v1"],
  }),
  updatePresetQuest(PACK_ID, {
    id: "preset.update.copper.sorting",
    title: "拿起、识别、归位，一条龙",
    description: "让铜傀儡完成一次取物并放入匹配铜箱子的完整整理循环。只拿起物品或走到箱边都不算成功。",
    completionMessage: "第一次自动整理闭环完成，仓库开始自己收拾。",
    chapterId: "update.copper",
    order: 6,
    rarity: "epic",
    reliability: "B",
    goals: [milestoneGoal("goal.complete_copper_sorting", "copper_golem.sort_success", "让铜傀儡完成一次自动整理循环")],
    gold: 500,
    experience: 180,
    requiredCapabilities: [CONTENT_CAP, "cap.event.copper_golem.sort_success.v1"],
    unlockRule: { type: "quest", questId: "preset.update.copper.golem", status: "completed" },
  }),
  updatePresetQuest(PACK_ID, {
    id: "preset.update.copper.shelf",
    title: "架子不是摆设，真能换货",
    description: "成功向架子放入或交换一次物品。必须确认架子库存发生有效交互，空手点一下不能算展示艺术。",
    completionMessage: "架子交互成功，物品展示开始兼顾实用。",
    chapterId: "update.copper",
    order: 7,
    rarity: "rare",
    reliability: "B",
    goals: [milestoneGoal("goal.use_shelf", "shelf.interact_success", "向架子成功放入或交换一次物品")],
    gold: 180,
    experience: 60,
    requiredCapabilities: [CONTENT_CAP, "cap.event.shelf.interact_success.v1"],
  }),
];

export const updateCopperPack: QuestPackDefinition = {
  id: PACK_ID,
  version: 1,
  title: "铜器时代，机器也发绿",
  description: "铜装备、铜傀儡和自动整理完整成包；默认关闭，确认世界支持对应正式内容后再启用。",
  category: "update",
  defaultEnabled: false,
  releaseState: "active",
  requiredCapabilities: [CONTENT_CAP],
  requiredGameplayExperiments: [],
  chapterIds: [updateCopperChapter.id],
};
