import type { QuestChapterDefinition, QuestDefinitionV2 } from "../../domain";
import { inventoryGoal, milestoneGoal, worldChapter, worldPresetQuest } from "../builders";

export const worldArchaeologyChapter: QuestChapterDefinition = worldChapter({
  id: "world.archaeology",
  title: "刷子一挥，历史掉落",
  description: "可疑方块、陶片和远古植物不会自己讲故事，你得带着刷子把线索一点点请出来。",
  order: 3,
  unlockRule: { type: "always" },
  questIds: [
    "preset.world.archaeology.brush",
    "preset.world.archaeology.brush_suspicious",
    "preset.world.archaeology.sherd",
    "preset.world.archaeology.pot",
    "preset.world.archaeology.sniffer_egg",
    "preset.world.archaeology.ancient_plants",
  ],
});

export const worldArchaeologyQuests: QuestDefinitionV2[] = [
  worldPresetQuest({
    id: "preset.world.archaeology.brush",
    title: "考古第一课：别拿镐砸",
    description: "让背包里出现一把刷子。面对可疑沙砾时，暴力拆迁只会毁掉线索，轻轻刷才是正确打开方式。",
    completionMessage: "刷子到手，历史遗物终于不用靠镐猜。",
    chapterId: "world.archaeology",
    order: 1,
    rarity: "common",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_brush", "selector.item.brush", 1, "背包中拥有一把刷子")],
    gold: 80,
    experience: 25,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.archaeology.brush_suspicious",
    title: "尘土散开，东西留下",
    description: "使用刷子从可疑沙或可疑砂砾中成功刷出一次物品。必须记录完整出土结果，挥两下刷子不能算考古发现。",
    completionMessage: "第一件出土物现身，尘土没有白吃。",
    chapterId: "world.archaeology",
    order: 2,
    rarity: "rare",
    reliability: "B",
    goals: [milestoneGoal("goal.brush_suspicious_block", "archaeology.brush_success", "从可疑方块中成功刷出物品")],
    gold: 160,
    experience: 55,
    requiredCapabilities: ["cap.event.archaeology.brush_success.v1"],
    unlockRule: { type: "quest", questId: "preset.world.archaeology.brush", status: "completed" },
  }),
  worldPresetQuest({
    id: "preset.world.archaeology.sherd",
    title: "碎归碎，故事还完整",
    description: "让背包里出现任意一种陶片。图案和来源不限，只要是正式陶片成员，就算找回了一小块历史。",
    completionMessage: "陶片已收藏，一段古老图案重新见光。",
    chapterId: "world.archaeology",
    order: 3,
    rarity: "rare",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_pottery_sherd", "selector.item.pottery_sherds", 1, "背包中拥有任意一种陶片")],
    gold: 180,
    experience: 60,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.archaeology.pot",
    title: "碎片开会，陶罐复工",
    description: "在找到陶片后，让背包里出现一个装饰陶罐。图案怎么搭配由你决定，古代审美不会发工单投诉。",
    completionMessage: "装饰陶罐完成，碎片重新拥有了完整轮廓。",
    chapterId: "world.archaeology",
    order: 4,
    rarity: "rare",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_decorated_pot", "selector.item.decorated_pot", 1, "背包中拥有一个装饰陶罐")],
    gold: 220,
    experience: 80,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
    unlockRule: { type: "quest", questId: "preset.world.archaeology.sherd", status: "completed" },
  }),
  worldPresetQuest({
    id: "preset.world.archaeology.sniffer_egg",
    title: "这颗蛋，闻起来很远古",
    description: "让背包里出现一颗嗅探兽蛋。它不是普通收藏品，而是一只远古大鼻子重新回到世界的起点。",
    completionMessage: "嗅探兽蛋已找到，失落生命等待孵化。",
    chapterId: "world.archaeology",
    order: 5,
    rarity: "epic",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_sniffer_egg", "selector.item.sniffer_egg", 1, "背包中拥有一颗嗅探兽蛋")],
    gold: 450,
    experience: 160,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.archaeology.ancient_plants",
    title: "远古花园，双苗到齐",
    description: "在找到嗅探兽蛋后，让背包里同时拥有火把花种子和瓶子草荚果。两种都在，远古花园才算凑齐开工材料。",
    completionMessage: "两种远古种子齐聚，花园跨时代开张。",
    chapterId: "world.archaeology",
    order: 6,
    rarity: "epic",
    reliability: "A",
    goals: [
      inventoryGoal("goal.possess_torchflower_seeds", "selector.item.torchflower_seeds", 1, "背包中拥有火把花种子"),
      inventoryGoal("goal.possess_pitcher_pod", "selector.item.pitcher_pod", 1, "背包中拥有瓶子草荚果"),
    ],
    gold: 350,
    experience: 120,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
    unlockRule: { type: "quest", questId: "preset.world.archaeology.sniffer_egg", status: "completed" },
  }),
];
