import type { QuestChapterDefinition, QuestDefinitionV2 } from "../../domain";
import { inventoryGoal, milestoneGoal, snapshotGoal, worldChapter, worldPresetQuest } from "../builders";

export const worldDeepdarkChapter: QuestChapterDefinition = worldChapter({
  id: "world.deepdark",
  title: "安静点，地底在听",
  description: "幽匿、古城和监守者共享同一片黑暗。这里最重要的生存技巧，有时就是别制造下一声。",
  order: 4,
  unlockRule: { type: "always" },
  questIds: [
    "preset.world.deepdark.sculk",
    "preset.world.deepdark.enter",
    "preset.world.deepdark.ancient_city",
    "preset.world.deepdark.echo_shard",
    "preset.world.deepdark.recovery_compass",
    "preset.world.deepdark.swift_sneak",
  ],
});

export const worldDeepdarkQuests: QuestDefinitionV2[] = [
  worldPresetQuest({
    id: "preset.world.deepdark.sculk",
    title: "这块地板，像在呼吸",
    description: "让背包里出现至少一个幽匿块。它安静时像普通装饰，一旦附近有动静，整片地底都会开始交换情报。",
    completionMessage: "幽匿块已收下，黑暗的触感有了实体。",
    chapterId: "world.deepdark",
    order: 1,
    rarity: "common",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_sculk", "selector.item.sculk", 1, "背包中拥有一个幽匿块")],
    gold: 120,
    experience: 40,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.deepdark.enter",
    title: "深暗之域，音量归零",
    description: "亲自进入深暗之域生物群系。系统必须确认当前生物群系，站在洞口听尖啸声不算真正到场。",
    completionMessage: "深暗之域已抵达，现在连脚步都显得很响。",
    chapterId: "world.deepdark",
    order: 2,
    rarity: "rare",
    reliability: "B",
    goals: [
      milestoneGoal("goal.enter_deep_dark", "player.biome_enter", "进入深暗之域生物群系", {
        filters: { biome: { op: "eq", value: "minecraft:deep_dark" } },
        backfillPolicy: "current_state",
        evidenceProviderId: "evidence.biome.current",
      }),
    ],
    gold: 220,
    experience: 80,
    requiredCapabilities: ["cap.event.player.biome_enter.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.deepdark.ancient_city",
    title: "整座城市，都在屏住呼吸",
    description: "亲自进入一座远古城市。只有可靠结构识别才会完成；回响碎片、唱片或附魔书都不能替你证明到场。",
    completionMessage: "远古城市已确认，寂静终于有了轮廓。",
    chapterId: "world.deepdark",
    order: 3,
    rarity: "epic",
    reliability: "C",
    goals: [
      milestoneGoal("goal.enter_ancient_city", "structure.enter", "亲自进入一座远古城市", {
        filters: { structure: { op: "eq", value: "minecraft:ancient_city" } },
      }),
    ],
    gold: 450,
    experience: 160,
    requiredCapabilities: ["cap.event.structure.enter.v1"],
    unlockRule: { type: "quest", questId: "preset.world.deepdark.enter", status: "completed" },
  }),
  worldPresetQuest({
    id: "preset.world.deepdark.echo_shard",
    title: "过去碎成了八小块",
    description: "让背包里同时拥有至少 8 个回响碎片。每一块都像在回放旧日噪声，八块凑齐就能指向更实际的用途。",
    completionMessage: "八枚回响碎片齐聚，过去开始指路。",
    chapterId: "world.deepdark",
    order: 4,
    rarity: "epic",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_echo_shards", "selector.item.echo_shards", 8, "背包中同时拥有 8 个回响碎片")],
    gold: 450,
    experience: 160,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.deepdark.recovery_compass",
    title: "上次倒下的地方，在这边",
    description: "在收集回响碎片后，让背包里出现一个追溯指针。它不会替你捡回装备，但至少能让遗物不再只靠记忆定位。",
    completionMessage: "追溯指针到手，翻车地点终于不再失联。",
    chapterId: "world.deepdark",
    order: 5,
    rarity: "epic",
    reliability: "A",
    goals: [
      inventoryGoal("goal.possess_recovery_compass", "selector.item.recovery_compass", 1, "背包中拥有一个追溯指针"),
    ],
    gold: 500,
    experience: 180,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
    unlockRule: { type: "quest", questId: "preset.world.deepdark.echo_shard", status: "completed" },
  }),
  worldPresetQuest({
    id: "preset.world.deepdark.swift_sneak",
    title: "蹲着走，也能走出残影",
    description: "持有一本带迅捷潜行的附魔书，或穿着带该附魔的装备。必须读取附魔组件，物品名称里写几个字不算。",
    completionMessage: "迅捷潜行已确认，蹲行从此不再像罚站。",
    chapterId: "world.deepdark",
    order: 6,
    rarity: "epic",
    reliability: "B",
    completeWhen: "any",
    goals: [
      inventoryGoal(
        "goal.possess_swift_sneak_item",
        "selector.enchantment.swift_sneak.inventory",
        1,
        "背包中持有带迅捷潜行的物品"
      ),
      snapshotGoal(
        "goal.equip_swift_sneak_item",
        "equipment",
        "selector.enchantment.swift_sneak.equipment",
        1,
        "装备带有迅捷潜行的护腿"
      ),
    ],
    gold: 600,
    experience: 220,
    requiredCapabilities: ["cap.snapshot.item_enchantment.v1", "cap.snapshot.equipment_enchantment.v1"],
  }),
];
