import type { QuestChapterDefinition, QuestDefinitionV2 } from "../../domain";
import { counterGoal, inventoryGoal, milestoneGoal, worldChapter, worldPresetQuest } from "../builders";

export const worldFarmChapter: QuestChapterDefinition = worldChapter({
  id: "world.farm",
  title: "白天种地，晚上数羊",
  description: "从第一批作物到忠诚伙伴，冒险之外也得把日子过起来，最好还能顺便收点蜂蜜。",
  order: 6,
  unlockRule: { type: "always" },
  questIds: [
    "preset.world.farm.plant",
    "preset.world.farm.harvest",
    "preset.world.farm.breed",
    "preset.world.farm.rancher",
    "preset.world.farm.tame",
    "preset.world.farm.honey",
  ],
});

export const worldFarmQuests: QuestDefinitionV2[] = [
  worldPresetQuest({
    id: "preset.world.farm.plant",
    title: "十六次弯腰，农田开张",
    description: "成功种植 16 次基础作物。必须是有效播种事件，把种子拿在手里对着土地发呆不会增加进度。",
    completionMessage: "十六株作物落地，农田终于像个长期项目。",
    chapterId: "world.farm",
    order: 1,
    rarity: "common",
    reliability: "B",
    goals: [counterGoal("goal.plant_crops", "crop.plant", 16, "成功种植 16 次基础作物")],
    gold: 100,
    experience: 30,
    requiredCapabilities: ["cap.event.crop.plant.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.farm.harvest",
    title: "成熟再收，拒绝拔苗助长",
    description: "累计收获 64 次或单位成熟基础作物。只有成熟收获会计数，刚种下就挖掉不叫丰收，叫返工。",
    completionMessage: "六十四份成熟收获入账，粮仓开始有底气。",
    chapterId: "world.farm",
    order: 2,
    rarity: "rare",
    reliability: "B",
    goals: [
      counterGoal("goal.harvest_mature_crops", "crop.harvest", 64, "累计收获 64 份成熟作物", {
        aggregation: "sum",
        field: "amount",
      }),
    ],
    gold: 180,
    experience: 60,
    requiredCapabilities: ["cap.event.crop.harvest.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.farm.breed",
    title: "两颗爱心，一个新成员",
    description: "成功繁殖一次动物。喂食动作只是开始，系统必须确认幼崽真正出生，爱心粒子不能单独交作业。",
    completionMessage: "第一只幼崽出生，牧场人口开始自然增长。",
    chapterId: "world.farm",
    order: 3,
    rarity: "common",
    reliability: "B",
    goals: [milestoneGoal("goal.breed_first_animal", "entity.breed", "成功繁殖一次动物")],
    gold: 120,
    experience: 40,
    requiredCapabilities: ["cap.event.entity.breed.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.farm.rancher",
    title: "爱心粒子，批量生产",
    description: "在第一次繁殖后累计成功繁殖 10 次动物。物种不限，每次都必须有可靠的新生结果。",
    completionMessage: "十次繁殖完成，牧场主身份正式生效。",
    chapterId: "world.farm",
    order: 4,
    rarity: "rare",
    reliability: "B",
    goals: [counterGoal("goal.breed_ten_animals", "entity.breed", 10, "累计成功繁殖 10 次动物")],
    gold: 260,
    experience: 90,
    requiredCapabilities: ["cap.event.entity.breed.v1"],
    unlockRule: { type: "quest", questId: "preset.world.farm.breed", status: "completed" },
  }),
  worldPresetQuest({
    id: "preset.world.farm.tame",
    title: "项圈一亮，队友上线",
    description: "成功驯服一只狼或猫。必须确认归属关系真正建立，递出骨头或鱼但被拒绝不算收获伙伴。",
    completionMessage: "忠诚伙伴加入队伍，独自旅行正式成为过去。",
    chapterId: "world.farm",
    order: 5,
    rarity: "rare",
    reliability: "B",
    goals: [
      milestoneGoal("goal.tame_wolf_or_cat", "entity.tame", "成功驯服一只狼或猫", {
        filters: { entity: { op: "in", value: ["minecraft:wolf", "minecraft:cat"] } },
        backfillPolicy: "historical",
        evidenceProviderId: "evidence.entity.tame.owner",
      }),
    ],
    gold: 220,
    experience: 80,
    requiredCapabilities: ["cap.event.entity.tame.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.farm.honey",
    title: "甜是甜，小心有刺",
    description: "让背包里出现一瓶蜂蜜。采集前记得照顾蜂群情绪，篝火和耐心通常比被整窝追着跑更体面。",
    completionMessage: "蜂蜜装瓶成功，这份甜没有白挨蜇。",
    chapterId: "world.farm",
    order: 6,
    rarity: "common",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_honey_bottle", "selector.item.honey_bottle", 1, "背包中拥有一瓶蜂蜜")],
    gold: 120,
    experience: 40,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
  }),
];
