import type { QuestChapterDefinition, QuestDefinitionV2 } from "../../domain";
import { counterGoal, inventoryGoal, milestoneGoal, snapshotGoal, worldChapter, worldPresetQuest } from "../builders";

export const worldOceanChapter: QuestChapterDefinition = worldChapter({
  id: "world.ocean",
  title: "下海可以，记得换气",
  description: "从海面一路摸到神殿深处，藏宝、守卫者与潮涌核心都在蓝色世界里等你。",
  order: 2,
  unlockRule: { type: "always" },
  questIds: [
    "preset.world.ocean.enter",
    "preset.world.ocean.treasure_map",
    "preset.world.ocean.heart",
    "preset.world.ocean.guardians",
    "preset.world.ocean.elder_guardian",
    "preset.world.ocean.sponge",
    "preset.world.ocean.conduit",
  ],
});

export const worldOceanQuests: QuestDefinitionV2[] = [
  worldPresetQuest({
    id: "preset.world.ocean.enter",
    title: "蓝色很美，氧气很贵",
    description: "亲自进入任意海洋类生物群系。站在岸边看海不算，系统必须可靠确认你已经踏进海洋区域。",
    completionMessage: "海洋区域已抵达，呼吸条开始参与冒险。",
    chapterId: "world.ocean",
    order: 1,
    rarity: "common",
    reliability: "B",
    goals: [
      milestoneGoal("goal.enter_ocean_biome", "player.biome_enter", "进入任意海洋类生物群系", {
        filters: { biomeCategory: { op: "eq", value: "ocean" } },
        backfillPolicy: "current_state",
        evidenceProviderId: "evidence.biome.current",
      }),
    ],
    gold: 120,
    experience: 40,
    requiredCapabilities: ["cap.event.player.biome_enter.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.ocean.treasure_map",
    title: "红叉已经替你加班了",
    description: "让背包里出现一张真正的藏宝图。普通空地图不算，必须通过地图组件确认它确实指向埋藏的宝藏。",
    completionMessage: "藏宝图确认无误，红叉正在远方等你。",
    chapterId: "world.ocean",
    order: 2,
    rarity: "rare",
    reliability: "B",
    goals: [inventoryGoal("goal.possess_treasure_map", "selector.item.treasure_maps", 1, "背包中拥有一张藏宝图")],
    gold: 150,
    experience: 50,
    requiredCapabilities: ["cap.snapshot.inventory.treasure_map.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.ocean.heart",
    title: "海洋把心落在箱子里",
    description: "让背包里出现一颗海洋之心。它暂时不会跳，但和鹦鹉螺壳组合之后，整片海域都会听见动静。",
    completionMessage: "海洋之心入手，潮涌计划有了核心。",
    chapterId: "world.ocean",
    order: 3,
    rarity: "epic",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_heart_of_sea", "selector.item.heart_of_the_sea", 1, "背包中拥有海洋之心")],
    gold: 350,
    experience: 120,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.ocean.guardians",
    title: "激光鱼，集体断电",
    description: "击杀 10 只守卫者。它们的激光锁定很认真，你的任务也很明确：让十束光依次熄灭。",
    completionMessage: "十只守卫者断电，神殿走廊安静了不少。",
    chapterId: "world.ocean",
    order: 4,
    rarity: "rare",
    reliability: "A",
    goals: [
      counterGoal("goal.kill_guardians", "entity.kill", 10, "击杀 10 只守卫者", {
        filters: { entity: { op: "eq", value: "minecraft:guardian" } },
      }),
    ],
    gold: 220,
    experience: 80,
    requiredCapabilities: ["cap.event.entity.kill.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.ocean.elder_guardian",
    title: "老鱼也得讲基本法",
    description: "亲手击杀一只远古守卫者。挖掘疲劳消失或捡到海绵都不算完成任务。",
    completionMessage: "远古守卫者倒下，神殿的压迫感少了一层。",
    chapterId: "world.ocean",
    order: 5,
    rarity: "epic",
    reliability: "A",
    goals: [
      milestoneGoal("goal.kill_elder_guardian", "entity.kill", "击杀一只远古守卫者", {
        filters: { entity: { op: "eq", value: "minecraft:elder_guardian" } },
      }),
    ],
    gold: 600,
    experience: 220,
    requiredCapabilities: ["cap.event.entity.kill.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.ocean.sponge",
    title: "吸水这事，它是专业的",
    description: "让背包里出现海绵或湿海绵。无论干湿，只要确实在背包中，就算拿到了海底工程队的核心设备。",
    completionMessage: "海绵已入库，大型排水工程有了底气。",
    chapterId: "world.ocean",
    order: 6,
    rarity: "rare",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_sponge", "selector.item.sponges", 1, "背包中拥有海绵或湿海绵")],
    gold: 220,
    experience: 80,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.ocean.conduit",
    title: "让大海给你开会员",
    description: "在玩家附近可靠检测到一座已经激活的潮涌核心。只把核心放进水里不算，完整结构和有效状态都必须成立。",
    completionMessage: "潮涌核心激活，附近海水开始提供增益服务。",
    chapterId: "world.ocean",
    order: 7,
    rarity: "epic",
    reliability: "B",
    goals: [
      snapshotGoal(
        "goal.activate_conduit",
        "nearby_world",
        "selector.world.active_conduit",
        1,
        "在附近激活一座潮涌核心",
        { maxDistance: 32 }
      ),
    ],
    gold: 700,
    experience: 260,
    requiredCapabilities: ["cap.snapshot.nearby_world.active_conduit.v1"],
    unlockRule: { type: "quest", questId: "preset.world.ocean.heart", status: "completed" },
  }),
];
