import type { QuestChapterDefinition, QuestDefinitionV2 } from "../../domain";
import { inventoryGoal, milestoneGoal, worldChapter, worldPresetQuest } from "../builders";

export const worldPaleGardenChapter: QuestChapterDefinition = worldChapter({
  id: "world.pale_garden",
  title: "花园很白，眼神很多",
  description: "苍白橡木、嘎枝和树脂共同组成一片不太欢迎夜间访客的森林，进去以后别忘了回头看。",
  order: 8,
  unlockRule: { type: "always" },
  questIds: [
    "preset.world.pale_garden.enter",
    "preset.world.pale_garden.pale_oak",
    "preset.world.pale_garden.creaking",
    "preset.world.pale_garden.heart",
    "preset.world.pale_garden.resin",
  ],
});

export const worldPaleGardenQuests: QuestDefinitionV2[] = [
  worldPresetQuest({
    id: "preset.world.pale_garden.enter",
    title: "颜色退场，花园登场",
    description: "亲自进入苍白之园生物群系。系统必须确认当前位置，远远看见灰白树冠不能算到此一游。",
    completionMessage: "苍白之园已抵达，周围颜色集体请假。",
    chapterId: "world.pale_garden",
    order: 1,
    rarity: "rare",
    reliability: "B",
    goals: [
      milestoneGoal("goal.enter_pale_garden", "player.biome_enter", "进入苍白之园生物群系", {
        filters: { biome: { op: "eq", value: "minecraft:pale_garden" } },
        backfillPolicy: "current_state",
        evidenceProviderId: "evidence.biome.current",
      }),
    ],
    gold: 180,
    experience: 60,
    requiredCapabilities: ["cap.event.player.biome_enter.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.pale_garden.pale_oak",
    title: "原木很白，装修很冷",
    description: "让背包里出现至少一块苍白橡木原木。它的色调像开了低饱和滤镜，建筑风格可以直接进入冷淡模式。",
    completionMessage: "苍白橡木入库，建筑配色少了一大截饱和度。",
    chapterId: "world.pale_garden",
    order: 2,
    rarity: "common",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_pale_oak_log", "selector.item.pale_oak_logs", 1, "背包中拥有苍白橡木原木")],
    gold: 100,
    experience: 35,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.pale_garden.creaking",
    title: "你一回头，它就守规矩",
    description: "在苍白之园与嘎枝产生一次有效接触或战斗。必须由专用遭遇证据确认，远处看到轮廓不算正式认识。",
    completionMessage: "嘎枝遭遇已记录，背后那道视线有了名字。",
    chapterId: "world.pale_garden",
    order: 3,
    rarity: "rare",
    reliability: "B",
    goals: [milestoneGoal("goal.encounter_creaking", "creaking.encounter", "与嘎枝产生一次有效遭遇")],
    gold: 250,
    experience: 90,
    requiredCapabilities: ["cap.event.creaking.encounter.v1"],
    unlockRule: { type: "quest", questId: "preset.world.pale_garden.enter", status: "completed" },
  }),
  worldPresetQuest({
    id: "preset.world.pale_garden.heart",
    title: "森林的心，硬得像木头",
    description: "让背包里出现一个嘎枝之心。它把嘎枝和森林连在一起，拆下来之后终于肯安静接受研究。",
    completionMessage: "嘎枝之心到手，森林里的控制中心已离线。",
    chapterId: "world.pale_garden",
    order: 4,
    rarity: "epic",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_creaking_heart", "selector.item.creaking_heart", 1, "背包中拥有一个嘎枝之心")],
    gold: 350,
    experience: 120,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.pale_garden.resin",
    title: "树脂一结，砖块有着落",
    description: "让背包里出现至少一种核心树脂物品，包括树脂团或树脂块。只有正式集合成员会匹配，染色赝品不算。",
    completionMessage: "树脂收藏到账，苍白森林留下了暖色纪念。",
    chapterId: "world.pale_garden",
    order: 5,
    rarity: "rare",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_resin", "selector.item.resin_items", 1, "背包中拥有树脂团或树脂块")],
    gold: 220,
    experience: 80,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
  }),
];
