import type { QuestChapterDefinition, QuestDefinitionV2 } from "../../domain";
import { inventoryGoal, milestoneGoal, worldChapter, worldPresetQuest } from "../builders";

export const worldRedstoneChapter: QuestChapterDefinition = worldChapter({
  id: "world.redstone",
  title: "机器不动，多半少根线",
  description: "红石、活塞和物流组件先备齐，再让自动合成器真正吐出第一件产品。工程从库存开始。",
  order: 7,
  unlockRule: { type: "always" },
  questIds: [
    "preset.world.redstone.redstone",
    "preset.world.redstone.piston",
    "preset.world.redstone.observer",
    "preset.world.redstone.comparator",
    "preset.world.redstone.hopper",
    "preset.world.redstone.crafter",
    "preset.world.redstone.crafter_use",
  ],
});

export const worldRedstoneQuests: QuestDefinitionV2[] = [
  worldPresetQuest({
    id: "preset.world.redstone.redstone",
    title: "红石先备十六份",
    description: "让背包里同时拥有至少 16 个红石粉。线路图可以稍后再画，工程开工前先确保导线不是空气。",
    completionMessage: "红石库存达标，第一条线路可以开铺。",
    chapterId: "world.redstone",
    order: 1,
    rarity: "common",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_redstone", "selector.item.redstone", 16, "背包中同时拥有 16 个红石粉")],
    gold: 80,
    experience: 25,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.redstone.piston",
    title: "方块不走，活塞来推",
    description: "在备好红石后，让背包里出现一个活塞。它不问建筑师想法，只负责把面前的方块认真推出一格。",
    completionMessage: "活塞到手，世界开始支持机械位移。",
    chapterId: "world.redstone",
    order: 2,
    rarity: "common",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_piston", "selector.item.piston", 1, "背包中拥有一个活塞")],
    gold: 100,
    experience: 35,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
    unlockRule: { type: "quest", questId: "preset.world.redstone.redstone", status: "completed" },
  }),
  worldPresetQuest({
    id: "preset.world.redstone.observer",
    title: "一张脸，盯住所有更新",
    description: "在备好红石后，让背包里出现一个侦测器。它会盯着前方方块的变化，比玩家盯机器排错更有耐心。",
    completionMessage: "侦测器已准备，方块更新从此有人值班。",
    chapterId: "world.redstone",
    order: 3,
    rarity: "common",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_observer", "selector.item.observer", 1, "背包中拥有一个侦测器")],
    gold: 100,
    experience: 35,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
    unlockRule: { type: "quest", questId: "preset.world.redstone.redstone", status: "completed" },
  }),
  worldPresetQuest({
    id: "preset.world.redstone.comparator",
    title: "信号也得比个大小",
    description: "在备好红石后，让背包里出现一个红石比较器。容器有多少货、信号该怎么选，它都能给出很理工的答案。",
    completionMessage: "比较器到手，信号终于学会了讲条件。",
    chapterId: "world.redstone",
    order: 4,
    rarity: "common",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_comparator", "selector.item.comparator", 1, "背包中拥有一个红石比较器")],
    gold: 100,
    experience: 35,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
    unlockRule: { type: "quest", questId: "preset.world.redstone.redstone", status: "completed" },
  }),
  worldPresetQuest({
    id: "preset.world.redstone.hopper",
    title: "物流第一步：漏斗上岗",
    description: "在备好红石后，让背包里出现一个漏斗。它长得像厨房用品，实际负责让物品自动排队搬家。",
    completionMessage: "漏斗到手，物品物流开始脱离人工搬运。",
    chapterId: "world.redstone",
    order: 5,
    rarity: "common",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_hopper", "selector.item.hopper", 1, "背包中拥有一个漏斗")],
    gold: 100,
    experience: 35,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
    unlockRule: { type: "quest", questId: "preset.world.redstone.redstone", status: "completed" },
  }),
  worldPresetQuest({
    id: "preset.world.redstone.crafter",
    title: "工作台开始自助营业",
    description: "在备好红石后，让背包里出现一个自动合成器。配方、输入和脉冲都安排好，它就能替双手接管重复劳动。",
    completionMessage: "自动合成器到手，工作台学会了自己上班。",
    chapterId: "world.redstone",
    order: 6,
    rarity: "rare",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_crafter", "selector.item.crafter", 1, "背包中拥有一个自动合成器")],
    gold: 180,
    experience: 60,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
    unlockRule: { type: "quest", questId: "preset.world.redstone.redstone", status: "completed" },
  }),
  worldPresetQuest({
    id: "preset.world.redstone.crafter_use",
    title: "机器一响，产品出厂",
    description: "让自动合成器成功输出一次物品。放下机器或塞入材料都不算，必须可靠确认一次完整合成输出。",
    completionMessage: "第一件自动合成产品出厂，机器正式转正。",
    chapterId: "world.redstone",
    order: 7,
    rarity: "rare",
    reliability: "B",
    goals: [milestoneGoal("goal.crafter_output", "crafter.output", "让自动合成器成功输出一次物品")],
    gold: 260,
    experience: 90,
    requiredCapabilities: ["cap.event.crafter.output.v1"],
    unlockRule: { type: "quest", questId: "preset.world.redstone.crafter", status: "completed" },
  }),
];
