import type { QuestChapterDefinition, QuestDefinitionV2 } from "../../domain";
import { counterGoal, inventoryGoal, milestoneGoal, worldChapter, worldPresetQuest } from "../builders";

export const worldTrialsChapter: QuestChapterDefinition = worldChapter({
  id: "world.trials",
  title: "密室不逃脱，怪得清完",
  description: "旋风人、钥匙、宝库和不祥试炼层层加码。这里没有主持人，只有不断刷新的考题。",
  order: 5,
  unlockRule: { type: "always" },
  questIds: [
    "preset.world.trials.enter",
    "preset.world.trials.breeze",
    "preset.world.trials.breeze_rod",
    "preset.world.trials.trial_key",
    "preset.world.trials.vault",
    "preset.world.trials.ominous",
    "preset.world.trials.ominous_key",
    "preset.world.trials.heavy_core",
    "preset.world.trials.mace",
  ],
});

export const worldTrialsQuests: QuestDefinitionV2[] = [
  worldPresetQuest({
    id: "preset.world.trials.enter",
    title: "铜墙后面，全是考题",
    description: "亲自进入一座试炼密室。只有可靠结构识别才会完成；捡到试炼钥匙或旋风棒不能倒推你来过。",
    completionMessage: "试炼密室已确认，第一轮机关开始转动。",
    chapterId: "world.trials",
    order: 1,
    rarity: "rare",
    reliability: "C",
    goals: [
      milestoneGoal("goal.enter_trial_chamber", "structure.enter", "亲自进入一座试炼密室", {
        filters: { structure: { op: "eq", value: "minecraft:trial_chambers" } },
      }),
    ],
    gold: 250,
    experience: 90,
    requiredCapabilities: ["cap.event.structure.enter.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.trials.breeze",
    title: "风很大，先打三只",
    description: "击杀 3 只旋风人。它们负责把你吹离计划路线，你负责让三股乱风依次停机。",
    completionMessage: "三只旋风人停转，现场终于没那么飘。",
    chapterId: "world.trials",
    order: 2,
    rarity: "rare",
    reliability: "A",
    goals: [
      counterGoal("goal.kill_breezes", "entity.kill", 3, "击杀 3 只旋风人", {
        filters: { entity: { op: "eq", value: "minecraft:breeze" } },
      }),
    ],
    gold: 250,
    experience: 90,
    requiredCapabilities: ["cap.event.entity.kill.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.trials.breeze_rod",
    title: "把一阵风握在手里",
    description: "让背包里出现至少一根旋风棒。它看着轻，能做出的东西却一个比一个擅长改变落点。",
    completionMessage: "旋风棒已收下，风终于有了实体库存。",
    chapterId: "world.trials",
    order: 3,
    rarity: "rare",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_breeze_rod", "selector.item.breeze_rod", 1, "背包中拥有一根旋风棒")],
    gold: 220,
    experience: 80,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.trials.trial_key",
    title: "钥匙有了，宝库别装睡",
    description: "让背包里出现一把普通试炼钥匙。它不是纪念品，而是让宝库停止摆架子的正式通行证。",
    completionMessage: "试炼钥匙到手，普通宝库进入可交涉状态。",
    chapterId: "world.trials",
    order: 4,
    rarity: "rare",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_trial_key", "selector.item.trial_key", 1, "背包中拥有一把试炼钥匙")],
    gold: 220,
    experience: 80,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.trials.vault",
    title: "钥匙转一下，宝库吐装备",
    description: "使用钥匙成功解锁一次普通宝库。靠近、互动失败或只看到别人开箱都不算，奖励必须由你的解锁操作产生。",
    completionMessage: "普通宝库成功开启，这次奖励确实归你。",
    chapterId: "world.trials",
    order: 5,
    rarity: "epic",
    reliability: "B",
    goals: [
      milestoneGoal("goal.unlock_normal_vault", "vault.unlock", "使用钥匙解锁一次普通宝库", {
        filters: { vaultType: { op: "eq", value: "normal" } },
      }),
    ],
    gold: 350,
    experience: 120,
    requiredCapabilities: ["cap.event.vault.unlock.v1"],
    unlockRule: { type: "quest", questId: "preset.world.trials.trial_key", status: "completed" },
  }),
  worldPresetQuest({
    id: "preset.world.trials.ominous",
    title: "难度旋钮，被你拧高了",
    description: "获得试炼之兆或进入有效的不祥试炼状态。必须由状态效果或专用试炼证据确认，喝空瓶子不算加码。",
    completionMessage: "不祥试炼已启动，密室决定认真招待你。",
    chapterId: "world.trials",
    order: 6,
    rarity: "epic",
    reliability: "B",
    goals: [
      milestoneGoal("goal.gain_trial_omen", "effect.gain", "获得试炼之兆效果", {
        filters: { effect: { op: "eq", value: "minecraft:trial_omen" } },
        backfillPolicy: "current_state",
        evidenceProviderId: "evidence.effect.current",
      }),
    ],
    gold: 350,
    experience: 120,
    requiredCapabilities: ["cap.event.effect.gain.v1", "cap.snapshot.effects.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.trials.ominous_key",
    title: "这把钥匙，黑得很贵",
    description: "进入不祥试炼后，让背包里出现一把不祥试炼钥匙。它颜色更深，承诺的奖励也更敢开价。",
    completionMessage: "不祥钥匙入袋，高级宝库该停止卖关子了。",
    chapterId: "world.trials",
    order: 7,
    rarity: "epic",
    reliability: "A",
    goals: [
      inventoryGoal("goal.possess_ominous_trial_key", "selector.item.ominous_trial_key", 1, "背包中拥有不祥试炼钥匙"),
    ],
    gold: 400,
    experience: 140,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
    unlockRule: { type: "quest", questId: "preset.world.trials.ominous", status: "completed" },
  }),
  worldPresetQuest({
    id: "preset.world.trials.heavy_core",
    title: "名字叫核心，重量也核心",
    description: "让背包里出现一个重型核心。它是宝库里少见的硬货，也是重锤配方最不愿意轻易出现的那一半。",
    completionMessage: "重型核心到手，重锤计划有了最沉的一块。",
    chapterId: "world.trials",
    order: 8,
    rarity: "epic",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_heavy_core", "selector.item.heavy_core", 1, "背包中拥有一个重型核心")],
    gold: 700,
    experience: 260,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.trials.mace",
    title: "下落速度，也能算攻击力",
    description: "在获得重型核心后，让背包里出现一把重锤。它会认真计算你的下落高度，也会放大落空时的尴尬。",
    completionMessage: "重锤完成，从高处落下终于有了战术名称。",
    chapterId: "world.trials",
    order: 9,
    rarity: "legendary",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_mace", "selector.item.mace", 1, "背包中拥有一把重锤")],
    gold: 1000,
    experience: 400,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
    unlockRule: { type: "quest", questId: "preset.world.trials.heavy_core", status: "completed" },
  }),
];
