import type { QuestChapterDefinition, QuestDefinitionV2 } from "../../domain";
import { inventoryGoal, milestoneGoal, worldChapter, worldPresetQuest, counterGoal } from "../builders";

export const worldVillageChapter: QuestChapterDefinition = worldChapter({
  id: "world.village",
  title: "村口经济学与防卫课",
  description: "先和村民谈生意，再替整座村庄处理不讲道理的访客。文明与战斗，这里两门都考。",
  order: 1,
  unlockRule: { type: "always" },
  questIds: [
    "preset.world.village.first_trade",
    "preset.world.village.trader",
    "preset.world.village.cure",
    "preset.world.village.ominous_bottle",
    "preset.world.village.raid",
    "preset.world.village.totem",
  ],
});

export const worldVillageQuests: QuestDefinitionV2[] = [
  worldPresetQuest({
    id: "preset.world.village.first_trade",
    title: "绿眼睛盯上了你的库存",
    description: "和村民成功完成一次交易。打开界面看看不算，必须真的交货并拿到对方给出的商品。",
    completionMessage: "第一笔村民交易成交，绿宝石开始流通。",
    chapterId: "world.village",
    order: 1,
    rarity: "common",
    reliability: "B",
    goals: [milestoneGoal("goal.complete_first_trade", "villager.trade", "成功完成一次村民交易")],
    gold: 100,
    experience: 35,
    requiredCapabilities: ["cap.event.villager.trade.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.village.trader",
    title: "绿宝石也有流水账",
    description: "在第一次成交后累计完成 10 次村民交易。买卖品种不限，但每一笔都必须由交易成功事件确认。",
    completionMessage: "十笔交易落账，你已经是村口熟面孔。",
    chapterId: "world.village",
    order: 2,
    rarity: "rare",
    reliability: "B",
    goals: [counterGoal("goal.complete_ten_trades", "villager.trade", 10, "累计完成 10 次村民交易")],
    gold: 200,
    experience: 70,
    requiredCapabilities: ["cap.event.villager.trade.v1"],
    unlockRule: { type: "quest", questId: "preset.world.village.first_trade", status: "completed" },
  }),
  worldPresetQuest({
    id: "preset.world.village.cure",
    title: "打折之前，先把人救回来",
    description: "成功治愈一名僵尸村民。虚弱效果、金苹果和漫长等待必须形成完整治愈结果，不能只做前半套。",
    completionMessage: "村民恢复理智，也记住了这份救命人情。",
    chapterId: "world.village",
    order: 3,
    rarity: "epic",
    reliability: "B",
    goals: [milestoneGoal("goal.cure_zombie_villager", "zombie_villager.cure", "成功治愈一名僵尸村民")],
    gold: 350,
    experience: 120,
    requiredCapabilities: ["cap.event.zombie_villager.cure.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.village.ominous_bottle",
    title: "这瓶子一看就不吉利",
    description: "让背包里出现任意等级的不祥之瓶。可以先收着，但喝之前最好确认村庄是否愿意配合你的冒险计划。",
    completionMessage: "不祥之瓶已入袋，麻烦也进入待命状态。",
    chapterId: "world.village",
    order: 4,
    rarity: "rare",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_ominous_bottle", "selector.item.ominous_bottles", 1, "背包中拥有任意不祥之瓶")],
    gold: 180,
    experience: 60,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
  }),
  worldPresetQuest({
    id: "preset.world.village.raid",
    title: "村庄保卫战，正式开席",
    description: "在拥有不祥之物后，参与并成功赢下一次袭击。只击倒几个灾厄村民不算，系统必须确认整场袭击胜利。",
    completionMessage: "袭击结束，村庄的钟终于能正常报时。",
    chapterId: "world.village",
    order: 5,
    rarity: "epic",
    reliability: "B",
    goals: [
      milestoneGoal("goal.win_raid", "raid.win", "成功赢下一次村庄袭击", {
        backfillPolicy: "historical",
        evidenceProviderId: "evidence.raid.win",
      }),
    ],
    gold: 700,
    experience: 260,
    requiredCapabilities: ["cap.event.raid.win.v1"],
    unlockRule: { type: "quest", questId: "preset.world.village.ominous_bottle", status: "completed" },
  }),
  worldPresetQuest({
    id: "preset.world.village.totem",
    title: "死亡申请，被驳回一次",
    description: "让背包里出现一个不死图腾。它不会让你永久无敌，但能在最尴尬的一次失误里替你按下撤回。",
    completionMessage: "不死图腾到手，生命多了一次撤回机会。",
    chapterId: "world.village",
    order: 6,
    rarity: "epic",
    reliability: "A",
    goals: [inventoryGoal("goal.possess_totem", "selector.item.totem_of_undying", 1, "背包中拥有一个不死图腾")],
    gold: 500,
    experience: 180,
    requiredCapabilities: ["cap.snapshot.inventory.v1"],
  }),
];
