// 此文件由脚本自动生成：文件名 → 实际私用区字符
export const glyphMap: Record<string, string> = {
  "3": "",
  "8": "",
  accept: "",
  accessories: "",
  ada: "",
  add: "",
  ah: "",
  altinkupa: "",
  altinmadalya: "",
  amongus: "",
  anahtar: "",
  angry: "",
  apartment_editor: "",
  archery: "",
  asker: "",
  auras: "",
  azrail: "",
  back: "",
  barber: "",
  bina: "",
  blacksmith: "",
  bronzkupa: "",
  buyutec: "",
  cancel: "",
  canta: "",
  carneval: "",
  carneval_unavailable: "",
  catalogue: "",
  championscore: "",
  chat_bubble_orange: "",
  chat_bubble_white: "",
  checkpoint: "",
  circle: "",
  clock: "",
  clown: "",
  coins: "",
  compass_00: "",
  copkutusu: "",
  crown: "",
  dead: "",
  deny: "",
  dice: "",
  dinazor: "",
  discord: "",
  dragon: "",
  dungeon: "",
  dunya: "",
  durbun: "",
  duyuru: "",
  edit2: "",
  emerald: "",
  exit: "",
  eyes: "",
  faces: "",
  fast_travel: "",
  fotograf: "",
  friends: "",
  friend_add: "",
  friend_remove: "",
  gadgets: "",
  gamepad: "",
  game_battle_box: "",
  game_hole_in_the_wall: "",
  game_parkour_tag: "",
  game_sky_battle: "",
  game_survival_games: "",
  game_tgttosawaf: "",
  gear: "",
  gem: "",
  gift: "",
  grin: "",
  gumuskupa: "",
  gumusmadalya: "",
  hats: "",
  heart: "",
  heart_blue: "",
  heart_eyes: "",
  heykel: "",
  home: "",
  infinibag: "",
  info: "",
  instagram: "",
  instance_selected: "",
  invite: "",
  iptaletmek: "",
  island: "",
  joy: "",
  kalp: "",
  kameraa: "",
  kilic: "",
  kupa: "",
  kupab: "",
  lands_1: "",
  lands_2: "",
  laughing: "",
  leave: "",
  leave_queue: "",
  mahkeme: "",
  map_kill_contract: "",
  marker_quest: "",
  mineral: "",
  mod_shield: "",
  music_note: "",
  nerd: "",
  noelbaba: "",
  overworld: "",
  party_invites: "",
  party_remove: "",
  party_unavailable: "",
  pickaxe: "",
  pizza: "",
  planor: "",
  play: "",
  point_left: "",
  point_right: "",
  profile: "",
  profile_2: "",
  quest_chest: "",
  quest_daily_common: "",
  quest_daily_weekly: "",
  quest_log: "",
  quest_world_unavaliable: "",
  region: "",
  requeue: "",
  requeue_random: "",
  rewards: "",
  saat: "",
  sandik: "",
  seed: "",
  settings: "",
  shop: "",
  shop_bank: "",
  shop_clothing: "",
  skull: "",
  social: "",
  spectator: "",
  star: "",
  sunglasses: "",
  sus: "",
  sword: "",
  telefonkulubesi: "",
  thinking: "",
  thumbs_down: "",
  thumbs_up: "",
  topraklar: "",
  trade: "",
  trampet: "",
  trophy: "",
  twitchh: "",
  twitter: "",
  upgrade: "",
  uye: "",
  uzayli: "",
  winner: "",
  wisdom: "",
  wood: "",
  youtubee: "",
  zombi: "",
};

// 头像（名字前缀）
export const namePrefixMap: string[] = [""];

// 欢迎语装饰
export const welcomeGlyphs: string[] = ["", "", "", "", "", "", "", "", ""];

// thedn装饰
// T H E D N
export const thendGlyphs: string[] = ["", "", "", "", ""];

// socials or 其他
export const socials: Record<string, string> = {
  youtube: "",
  reddit: "",
  note: "",
  twitter: "",
  discord: "",
  mcpedl: "",
};

// 其他
export const otherGlyphMap: Record<string, string> = {
  cat: "",
  gear: "",
  wrench: "",
};

// 商品分类图标
export const officeShopCategoryIcons: [string[], string[]] = [
  [
    "pizza",
    "wood",
    "pickaxe",
    "8",
    "mineral",
    "emerald",
    "3",
    "sword",
    "seed",
    "trophy",
    "kilic",
    "kalp",
    "infinibag",
    "hats",
    "gift",
    "gem",
    "dice",
    "dead",
    "archery",
    "accessories",
  ],
  [
    glyphMap["pizza"],
    glyphMap["wood"],
    glyphMap["pickaxe"],
    glyphMap["8"],
    glyphMap["mineral"],
    glyphMap["emerald"],
    glyphMap["3"],
    glyphMap["sword"],
    glyphMap["seed"],
    glyphMap["trophy"],
    glyphMap["kilic"],
    glyphMap["kalp"],
    glyphMap["infinibag"],
    glyphMap["hats"],
    glyphMap["gift"],
    glyphMap["gem"],
    glyphMap["dice"],
    glyphMap["dead"],
    glyphMap["archery"],
    glyphMap["accessories"],
  ],
];

// welcome fox
export const welcomeFoxGlyphs: string[] = [""];

export const glyphKeys = Object.keys(glyphMap) as GlyphKey[];

export const glyphList = Object.values(glyphMap);

export type GlyphKey = keyof typeof glyphMap;
