import type { QuestChapterDefinition, QuestDefinitionV2, QuestPackDefinition } from "../../domain";
import { creeperChapter, creeperPresetQuest, milestoneGoal } from "../builders";

export const creeperGuideChapter: QuestChapterDefinition = creeperChapter({
  id: "creeper.guide",
  title: "菜单不咬人，点开看看",
  description: "从第一次打开菜单到加入公会，把服务器常用功能真正走一遍，告别靠聊天猜命令。",
  order: 1,
  unlockRule: { type: "always" },
  questIds: [
    "preset.creeper.guide.open_menu",
    "preset.creeper.guide.waypoint",
    "preset.creeper.guide.tpa",
    "preset.creeper.guide.random_tp",
    "preset.creeper.guide.land",
    "preset.creeper.guide.public_waypoint",
    "preset.creeper.guide.market",
    "preset.creeper.guide.red_packet",
    "preset.creeper.guide.guild",
  ],
});

const OPEN_MENU = { type: "quest" as const, questId: "preset.creeper.guide.open_menu", status: "completed" as const };

export const creeperGuideQuests: QuestDefinitionV2[] = [
  creeperPresetQuest({
    id: "preset.creeper.guide.open_menu",
    title: "苦力怕菜单，第一次营业",
    description: "成功打开一次苦力怕主菜单。必须由菜单真正展示后的业务事件确认，只点按钮但界面打开失败不算。",
    completionMessage: "菜单成功打开，服务器功能终于不再藏着。",
    chapterId: "creeper.guide",
    order: 1,
    rarity: "common",
    reliability: "A",
    goals: [milestoneGoal("goal.open_creeper_menu", "creeper.menu.open", "成功打开一次苦力怕主菜单")],
    gold: 30,
    experience: 10,
    requiredCapabilities: ["cap.event.creeper.menu.open.v1"],
  }),
  creeperPresetQuest({
    id: "preset.creeper.guide.waypoint",
    title: "这里不错，给地图钉一下",
    description: "成功创建第一个个人路点。保存必须真正提交；若系统能可靠确认已有个人路点，也允许按当前状态回填。",
    completionMessage: "个人路点已保存，下次不用靠地形认路。",
    chapterId: "creeper.guide",
    order: 2,
    rarity: "common",
    reliability: "A",
    goals: [
      milestoneGoal("goal.create_personal_waypoint", "creeper.waypoint.create", "成功创建一个个人路点", {
        backfillPolicy: "current_state",
        evidenceProviderId: "evidence.creeper.waypoint.exists",
      }),
    ],
    gold: 80,
    experience: 25,
    requiredCapabilities: ["cap.event.creeper.waypoint.create.v1", "cap.snapshot.creeper_state.v1"],
    unlockRule: OPEN_MENU,
  }),
  creeperPresetQuest({
    id: "preset.creeper.guide.tpa",
    title: "你别动，我传过去",
    description: "成功完成一次玩家传送请求。发出申请或对方点同意都只是过程，必须确认传送最终执行成功。",
    completionMessage: "第一次 TPA 完成，找朋友不再靠长途跋涉。",
    chapterId: "creeper.guide",
    order: 3,
    rarity: "common",
    reliability: "A",
    goals: [milestoneGoal("goal.complete_tpa", "creeper.tpa.complete", "成功完成一次 TPA")],
    gold: 100,
    experience: 35,
    requiredCapabilities: ["cap.event.creeper.tpa.complete.v1"],
    unlockRule: OPEN_MENU,
  }),
  creeperPresetQuest({
    id: "preset.creeper.guide.random_tp",
    title: "坐标随机，勇气固定",
    description: "成功完成一次随机传送。必须确认安全落点和传送结果，点下按钮却因冷却或费用失败不算出发。",
    completionMessage: "随机传送成功，远方替你选好了落脚点。",
    chapterId: "creeper.guide",
    order: 4,
    rarity: "common",
    reliability: "A",
    goals: [milestoneGoal("goal.complete_random_tp", "creeper.random_tp.complete", "成功完成一次随机传送")],
    gold: 80,
    experience: 25,
    requiredCapabilities: ["cap.event.creeper.random_tp.complete.v1"],
    unlockRule: OPEN_MENU,
  }),
  creeperPresetQuest({
    id: "preset.creeper.guide.land",
    title: "这块地，从此有主",
    description: "成功创建第一块领地。范围与数据必须保存完成；若系统能可靠确认你已有领地，也允许按当前所有权回填。",
    completionMessage: "第一块领地创建完成，边界终于有了名字。",
    chapterId: "creeper.guide",
    order: 5,
    rarity: "rare",
    reliability: "A",
    goals: [
      milestoneGoal("goal.create_land", "creeper.land.create", "成功创建第一块领地", {
        backfillPolicy: "current_state",
        evidenceProviderId: "evidence.creeper.land.exists",
      }),
    ],
    gold: 200,
    experience: 70,
    requiredCapabilities: ["cap.event.creeper.land.create.v1", "cap.snapshot.creeper_state.v1"],
    unlockRule: OPEN_MENU,
  }),
  creeperPresetQuest({
    id: "preset.creeper.guide.public_waypoint",
    title: "服务器地标，刷卡抵达",
    description: "成功使用一次公共路点。浏览列表不算，必须由公共路点服务确认玩家已经完成对应传送。",
    completionMessage: "公共路点使用成功，服务器交通网正式接入。",
    chapterId: "creeper.guide",
    order: 6,
    rarity: "common",
    reliability: "A",
    goals: [milestoneGoal("goal.use_public_waypoint", "creeper.public_waypoint.use", "成功使用一次公共路点")],
    gold: 80,
    experience: 25,
    requiredCapabilities: ["cap.event.creeper.public_waypoint.use.v1"],
    unlockRule: OPEN_MENU,
  }),
  creeperPresetQuest({
    id: "preset.creeper.guide.market",
    title: "第一笔生意，流水落账",
    description: "在玩家市场成功完成一次买入或卖出。挂单、浏览和取消都不算，必须有可靠交易流水证明成交。",
    completionMessage: "市场首单成交，你的经济活动留下了记录。",
    chapterId: "creeper.guide",
    order: 7,
    rarity: "rare",
    reliability: "A",
    goals: [
      milestoneGoal("goal.complete_market_trade", "creeper.market.trade", "成功完成一次玩家市场交易", {
        backfillPolicy: "historical",
        evidenceProviderId: "evidence.creeper.market.trade",
      }),
    ],
    gold: 180,
    experience: 60,
    requiredCapabilities: ["cap.event.creeper.market.trade.v1"],
    unlockRule: OPEN_MENU,
  }),
  creeperPresetQuest({
    id: "preset.creeper.guide.red_packet",
    title: "红包一响，快乐到账",
    description: "成功发出或领取一次红包。打开页面和抢空都不算，红包业务必须确认一次有效资金或物品流转。",
    completionMessage: "红包互动成功，服务器气氛立刻热闹了一点。",
    chapterId: "creeper.guide",
    order: 8,
    rarity: "common",
    reliability: "A",
    goals: [milestoneGoal("goal.use_red_packet", "creeper.red_packet", "成功发出或领取一次红包")],
    gold: 120,
    experience: 40,
    requiredCapabilities: ["cap.event.creeper.red_packet.v1"],
    unlockRule: OPEN_MENU,
  }),
  creeperPresetQuest({
    id: "preset.creeper.guide.guild",
    title: "一个人开荒，一群人整活",
    description: "成功加入或创建一个公会。申请提交不算，必须确认成员关系建立；已有公会状态可可靠回填。",
    completionMessage: "公会关系已确认，冒险从单排进入组队。",
    chapterId: "creeper.guide",
    order: 9,
    rarity: "rare",
    reliability: "A",
    goals: [
      milestoneGoal("goal.join_or_create_guild", "creeper.guild.join_or_create", "成功加入或创建一个公会", {
        backfillPolicy: "current_state",
        evidenceProviderId: "evidence.creeper.guild.joined",
      }),
    ],
    gold: 200,
    experience: 70,
    requiredCapabilities: ["cap.event.creeper.guild.join_or_create.v1", "cap.snapshot.creeper_state.v1"],
    unlockRule: OPEN_MENU,
  }),
];

export const creeperGuidePack: QuestPackDefinition = {
  id: "preset.creeper",
  version: 1,
  title: "服务器功能，别靠猜",
  description: "九个轻量任务带你真正用过菜单、传送、领地、市场和公会；全部默认关闭，由管理员选择教学范围。",
  category: "creeper",
  defaultEnabled: false,
  releaseState: "active",
  requiredCapabilities: [],
  requiredGameplayExperiments: [],
  chapterIds: [creeperGuideChapter.id],
};
